### ISSUE TITLE
Build is suddenly broken with react 15.1.0

### ISSUE THREAD

**Issue by rvetere** [AdmitHub/meteor-buildpack-horse#108]
Nothing happened to our project repo at all and suddenly the heroku build is broken:

```
remote: react-helmet@3.1.0 node_modules/react-helmet
remote: ├── object-assign@4.1.0
remote: ├── deep-equal@1.0.1
remote: ├── warning@2.1.0 (loose-envify@1.2.0)
remote: ├── shallowequal@0.2.2 (lodash.keys@3.1.2)
remote: └── react-side-effect@1.0.2 (fbjs@0.1.0-alpha.10)
remote: 
remote: react@15.1.0 node_modules/react
remote: ├── object-assign@4.1.0
remote: ├── loose-envify@1.2.0 (js-tokens@1.0.3)
remote: └── fbjs@0.8.3 (ua-parser-js@0.7.10, promise@7.1.1, isomorphic-fetch@2.2.1, core-js@1.2.6)
remote: -----> Building Meteor with ROOT_URL: https://rotulorum-develop.herokuapp.com
remote: TypeError: undefined is not a function
remote:     at config (eval at readPackageConfig (packages/webpack:webpack/plugin/WebpackCompiler.js:301:28), <anonymous>:49:18)
remote:     at packages/webpack:webpack/plugin/WebpackCompiler.js:322:26
remote:     at Array.forEach (native)
remote:     at Object.load (packages/webpack:webpack/plugin/WebpackCompiler.js:320:15)
remote:     at WebpackCompiler.processFilesForTarget (packages/webpack:webpack/plugin/WebpackCompiler.js:130:13)
remote:     at __bottom_mark__ (/tools/utils/parse-stack.js:59:14)
remote:     at /tools/isobuild/compiler-plugin.js:187:13
remote:     at /tools/utils/buildmessage.js:359:18
remote:     at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
remote:     at /tools/utils/buildmessage.js:352:34
remote:     at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
remote:     at /tools/utils/buildmessage.js:350:23
remote:     at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
remote:     at Object.enterJob (/tools/utils/buildmessage.js:324:26)
remote:     at /tools/isobuild/compiler-plugin.js:176:22
remote:     at Function.time (/tools/tool-env/profile.js:305:10)
remote:     at /tools/isobuild/compiler-plugin.js:175:15
remote:     at Function._.each._.forEach (/tmp/buildpack20160530-162-1a8hntt/meteor-O3ol/.meteor/packages/meteor-tool/.1.3.2_4.10vjklo++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:87:22)
remote:     at CompilerPluginProcessor.runCompilerPlugins (/tools/isobuild/compiler-plugin.js:165:7)
remote:     at ClientTarget._runCompilerPlugins (/tools/isobuild/bundler.js:901:22)
remote:     at /tools/isobuild/bundler.js:681:34
remote:     at /tools/utils/buildmessage.js:359:18
remote:     at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
remote:     at /tools/utils/buildmessage.js:352:34
remote:     at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
remote:     at /tools/utils/buildmessage.js:350:23
remote:     at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
remote:     at Object.enterJob (/tools/utils/buildmessage.js:324:26)
remote:     at ClientTarget.make (/tools/isobuild/bundler.js:675:18)
remote:     at /tools/isobuild/bundler.js:2474:14
remote:     at /tools/isobuild/bundler.js:2563:20
remote:     at Array.forEach (native)
remote:     at Function._.each._.forEach (/tmp/buildpack20160530-162-1a8hntt/meteor-O3ol/.meteor/packages/meteor-tool/.1.3.2_4.10vjklo++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:79:11)
remote:     at /tools/isobuild/bundler.js:2562:7
remote:     at /tools/utils/buildmessage.js:271:13
remote:     at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
remote:     at /tools/utils/buildmessage.js:264:29
remote:     at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
remote:     at /tools/utils/buildmessage.js:262:18
remote:     at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
remote:     at /tools/utils/buildmessage.js:253:23
remote:     at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
remote:     at Object.capture (/tools/utils/buildmessage.js:252:19)
remote:     at Object.exports.bundle (/tools/isobuild/bundler.js:2455:31)
remote:     at buildCommand (/tools/cli/commands.js:909:30)
remote:     at Command.main.registerCommand._.extend.name [as func] (/tools/cli/commands.js:789:12)
remote:     at /tools/cli/main.js:1402:23
remote: TypeError: Cannot call method 'extract' of undefined
remote:     at config (eval at readPackageConfig (packages/webpack:webpack/plugin/WebpackCompiler.js:301:28), <anonymous>:35:35)
remote:     at packages/webpack:webpack/plugin/WebpackCompiler.js:322:26
remote:     at Array.forEach (native)
remote:     at Object.load (packages/webpack:webpack/plugin/WebpackCompiler.js:320:15)
remote:     at WebpackCompiler.processFilesForTarget (packages/webpack:webpack/plugin/WebpackCompiler.js:130:13)
remote:     at __bottom_mark__ (/tools/utils/parse-stack.js:59:14)
remote:     at /tools/isobuild/compiler-plugin.js:187:13
remote:     at /tools/utils/buildmessage.js:359:18
remote:     at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
remote:     at /tools/utils/buildmessage.js:352:34
remote:     at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
remote:     at /tools/utils/buildmessage.js:350:23
remote:     at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
remote:     at Object.enterJob (/tools/utils/buildmessage.js:324:26)
remote:     at /tools/isobuild/compiler-plugin.js:176:22
remote:     at Function.time (/tools/tool-env/profile.js:305:10)
remote:     at /tools/isobuild/compiler-plugin.js:175:15
remote:     at Function._.each._.forEach (/tmp/buildpack20160530-162-1a8hntt/meteor-O3ol/.meteor/packages/meteor-tool/.1.3.2_4.10vjklo++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:87:22)
remote:     at CompilerPluginProcessor.runCompilerPlugins (/tools/isobuild/compiler-plugin.js:165:7)
remote:     at ClientTarget._runCompilerPlugins (/tools/isobuild/bundler.js:901:22)
remote:     at /tools/isobuild/bundler.js:681:34
remote:     at /tools/utils/buildmessage.js:359:18
remote:     at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
remote:     at /tools/utils/buildmessage.js:352:34
remote:     at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
remote:     at /tools/utils/buildmessage.js:350:23
remote:     at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
remote:     at Object.enterJob (/tools/utils/buildmessage.js:324:26)
remote:     at ClientTarget.make (/tools/isobuild/bundler.js:675:18)
remote:     at /tools/isobuild/bundler.js:2474:14
remote:     at /tools/isobuild/bundler.js:2563:20
remote:     at Array.forEach (native)
remote:     at Function._.each._.forEach (/tmp/buildpack20160530-162-1a8hntt/meteor-O3ol/.meteor/packages/meteor-tool/.1.3.2_4.10vjklo++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:79:11)
remote:     at /tools/isobuild/bundler.js:2562:7
remote:     at /tools/utils/buildmessage.js:271:13
remote:     at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
remote:     at /tools/utils/buildmessage.js:264:29
remote:     at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
remote:     at /tools/utils/buildmessage.js:262:18
remote:     at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
remote:     at /tools/utils/buildmessage.js:253:23
remote:     at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
remote:     at Object.capture (/tools/utils/buildmessage.js:252:19)
remote:     at Object.exports.bundle (/tools/isobuild/bundler.js:2455:31)
remote:     at buildCommand (/tools/cli/commands.js:909:30)
remote:     at Command.main.registerCommand._.extend.name [as func] (/tools/cli/commands.js:789:12)
remote:     at /tools/cli/main.js:1402:23
remote: Errors prevented bundling:
remote: While processing files with webpack:webpack (for target web.browser):
remote: error: Can't load npm module
remote: '/tmp/build_f02693d43f91c9d0f2bfa3d1b2931936/node_modules/extract-text-webpack-plugin'
remote: from packages/webpack_npmworkaround.js. Check your Npm.depends().
remote: src/client.js: Entry module not found: Error: Cannot resolve module 'babel' in
remote: /tmp/build_f02693d43f91c9d0f2bfa3d1b2931936
remote: resolve module babel in /tmp/build_f02693d43f91c9d0f2bfa3d1b2931936
remote: looking for modules in
remote: /tmp/build_f02693d43f91c9d0f2bfa3d1b2931936/node_modules
remote: module variation babel-webpack-loader
remote: /tmp/build_f02693d43f91c9d0f2bfa3d1b2931936/node_modules/babel-webpack-loader
remote: doesn't exist (module as directory)
remote: resolve 'file' babel-webpack-loader in
remote: /tmp/build_f02693d43f91c9d0f2bfa3d1b2931936/node_modules
remote: resolve file
remote: /tmp/build_f02693d43f91c9d0f2bfa3d1b2931936/node_modules/babel-webpack-loader
remote: doesn't exist
remote: 
remote: /tmp/build_f02693d43f91c9d0f2bfa3d1b2931936/node_modules/babel-webpack-loader.webpack-loader.js
remote: doesn't exist
remote: 
remote: /tmp/build_f02693d43f91c9d0f2bfa3d1b2931936/node_modules/babel-webpack-loader.web-loader.js
remote: doesn't exist
remote: 
remote: /tmp/build_f02693d43f91c9d0f2bfa3d1b2931936/node_modules/babel-webpack-loader.loader.js
remote: doesn't exist
remote: 
remote: /tmp/build_f02693d43f91c9d0f2bfa3d1b2931936/node_modules/babel-webpack-loader.js
remote: doesn't exist
remote: module variation babel-web-loader
remote: /tmp/build_f02693d43f91c9d0f2bfa3d1b2931936/node_modules/babel-web-loader
remote: doesn't exist (module as directory)
remote: resolve 'file' babel-web-loader in
remote: /tmp/build_f02693d43f91c9d0f2bfa3d1b2931936/node_modules
remote: resolve file
remote: /tmp/build_f02693d43f91c9d0f2bfa3d1b2931936/node_modules/babel-web-loader
remote: doesn't exist
remote: 
remote: /tmp/build_f02693d43f91c9d0f2bfa3d1b2931936/node_modules/babel-web-loader.webpack-loader.js
remote: doesn't exist
remote: 
remote: /tmp/build_f02693d43f91c9d0f2bfa3d1b2931936/node_modules/babel-web-loader.web-loader.js
remote: doesn't exist
remote: 
remote: /tmp/build_f02693d43f91c9d0f2bfa3d1b2931936/node_modules/babel-web-loader.loader.js
remote: doesn't exist
remote: /tmp/build_f02693d43f91c9d0f2bfa3d1b2931936/node_modules/babel-web-loader.js
remote: doesn't exist
remote: module variation babel-loader
remote: /tmp/build_f02693d43f91c9d0f2bfa3d1b2931936/node_modules/babel-loader doesn't
remote: exist (module as directory)
remote: resolve 'file' babel-loader in
remote: /tmp/build_f02693d43f91c9d0f2bfa3d1b2931936/node_modules
remote: resolve file
remote: /tmp/build_f02693d43f91c9d0f2bfa3d1b2931936/node_modules/babel-loader doesn't
remote: exist
remote: 
remote: /tmp/build_f02693d43f91c9d0f2bfa3d1b2931936/node_modules/babel-loader.webpack-loader.js
remote: doesn't exist
remote: 
remote: /tmp/build_f02693d43f91c9d0f2bfa3d1b2931936/node_modules/babel-loader.web-loader.js
remote: doesn't exist
remote: /tmp/build_f02693d43f91c9d0f2bfa3d1b2931936/node_modules/babel-loader.loader.js
remote: doesn't exist
remote: /tmp/build_f02693d43f91c9d0f2bfa3d1b2931936/node_modules/babel-loader.js
remote: doesn't exist
remote: module variation babel
remote: /tmp/build_f02693d43f91c9d0f2bfa3d1b2931936/node_modules/babel doesn't exist
remote: (module as directory)
remote: resolve 'file' babel in
remote: /tmp/build_f02693d43f91c9d0f2bfa3d1b2931936/node_modules
remote: resolve file
remote: /tmp/build_f02693d43f91c9d0f2bfa3d1b2931936/node_modules/babel doesn't
remote: exist
remote: 
remote: /tmp/build_f02693d43f91c9d0f2bfa3d1b2931936/node_modules/babel.webpack-loader.js
remote: doesn't exist
remote: /tmp/build_f02693d43f91c9d0f2bfa3d1b2931936/node_modules/babel.web-loader.js
remote: doesn't exist
remote: /tmp/build_f02693d43f91c9d0f2bfa3d1b2931936/node_modules/babel.loader.js
remote: doesn't exist
remote: /tmp/build_f02693d43f91c9d0f2bfa3d1b2931936/node_modules/babel.js doesn't
remote: exist
remote: 
remote: While processing files with webpack:webpack (for target os.linux.x86_64):
remote: src/server.js: Entry module not found: Error: Cannot resolve module 'babel' in
remote: /tmp/build_f02693d43f91c9d0f2bfa3d1b2931936
remote: resolve module babel in /tmp/build_f02693d43f91c9d0f2bfa3d1b2931936
remote: looking for modules in
remote: /tmp/build_f02693d43f91c9d0f2bfa3d1b2931936/node_modules
remote: module variation babel-webpack-node-loader
remote: 
remote: /tmp/build_f02693d43f91c9d0f2bfa3d1b2931936/node_modules/babel-webpack-node-loader
remote: doesn't exist (module as directory)
remote: resolve 'file' babel-webpack-node-loader in
remote: /tmp/build_f02693d43f91c9d0f2bfa3d1b2931936/node_modules
remote: resolve file
remote: 
remote: /tmp/build_f02693d43f91c9d0f2bfa3d1b2931936/node_modules/babel-webpack-node-loader
remote: doesn't exist
remote: 
remote: /tmp/build_f02693d43f91c9d0f2bfa3d1b2931936/node_modules/babel-webpack-node-loader.webpack-node-loader.js
remote: doesn't exist
remote: 
remote: /tmp/build_f02693d43f91c9d0f2bfa3d1b2931936/node_modules/babel-webpack-node-loader.loader.js
remote: doesn't exist
remote: 
remote: /tmp/build_f02693d43f91c9d0f2bfa3d1b2931936/node_modules/babel-webpack-node-loader.js
remote: doesn't exist
remote: module variation babel-node-loader
remote: /tmp/build_f02693d43f91c9d0f2bfa3d1b2931936/node_modules/babel-node-loader
remote: doesn't exist (module as directory)
remote: resolve 'file' babel-node-loader in
remote: /tmp/build_f02693d43f91c9d0f2bfa3d1b2931936/node_modules
remote: resolve file
remote: /tmp/build_f02693d43f91c9d0f2bfa3d1b2931936/node_modules/babel-node-loader
remote: doesn't exist
remote: 
remote: /tmp/build_f02693d43f91c9d0f2bfa3d1b2931936/node_modules/babel-node-loader.webpack-node-loader.js
remote: doesn't exist
remote: 
remote: /tmp/build_f02693d43f91c9d0f2bfa3d1b2931936/node_modules/babel-node-loader.loader.js
remote: doesn't exist
remote: /tmp/build_f02693d43f91c9d0f2bfa3d1b2931936/node_modules/babel-node-loader.js
remote: doesn't exist
remote: module variation babel-loader
remote: /tmp/build_f02693d43f91c9d0f2bfa3d1b2931936/node_modules/babel-loader doesn't
remote: exist (module as directory)
remote: resolve 'file' babel-loader in
remote: /tmp/build_f02693d43f91c9d0f2bfa3d1b2931936/node_modules
remote: resolve file
remote: /tmp/build_f02693d43f91c9d0f2bfa3d1b2931936/node_modules/babel-loader doesn't
remote: exist
remote: 
remote: /tmp/build_f02693d43f91c9d0f2bfa3d1b2931936/node_modules/babel-loader.webpack-node-loader.js
remote: doesn't exist
remote: /tmp/build_f02693d43f91c9d0f2bfa3d1b2931936/node_modules/babel-loader.loader.js
remote: doesn't exist
remote: /tmp/build_f02693d43f91c9d0f2bfa3d1b2931936/node_modules/babel-loader.js
remote: doesn't exist
remote: module variation babel
remote: /tmp/build_f02693d43f91c9d0f2bfa3d1b2931936/node_modules/babel doesn't exist
remote: (module as directory)
remote: resolve 'file' babel in
remote: /tmp/build_f02693d43f91c9d0f2bfa3d1b2931936/node_modules
remote: resolve file
remote: /tmp/build_f02693d43f91c9d0f2bfa3d1b2931936/node_modules/babel doesn't
remote: exist
remote: 
remote: /tmp/build_f02693d43f91c9d0f2bfa3d1b2931936/node_modules/babel.webpack-node-loader.js
remote: doesn't exist
remote: /tmp/build_f02693d43f91c9d0f2bfa3d1b2931936/node_modules/babel.loader.js
remote: doesn't exist
remote: /tmp/build_f02693d43f91c9d0f2bfa3d1b2931936/node_modules/babel.js doesn't exist
remote: 
remote: 
remote:  !     Push rejected, failed to compile Node.js app
remote: 
remote: Verifying deploy...
remote: 
remote: !	Push rejected to rotulorum-develop.
remote: 
```

After closley looking to the error message, it turned out that he just sees a newer package of all rect things. So i updated them in my package.json too in hope i will run into the same error. No luck, the full project is running fine locally in dev mode and built for production.

**Comment by AdamBrodzinski** [comment]
Can you try deploy a todo app with React 15.1.0 to confirm this is the issue? It looks like this is a Webpack compilation error to me.

For a sanity check can you confirm that your package.json has React in it?

**Comment by rvetere** [comment]
Good approach - i'll try it with a simple todos app again this evening and let you know what my results are.

In the meanwhile - my package.json entries:

```
"dependencies": {
    "immutable": "^3.8.1",
    "milligram": "^1.1.0",
    "react": "^15.1.0",
    "react-addons-pure-render-mixin": "^15.1.0",
    "react-dom": "^15.1.0",
    "react-helmet": "^3.1.0",
    "react-mixin": "^3.0.5",
    "react-redux": "^4.4.5",
    "react-router": "^2.4.1",
    "react-router-redux": "^4.0.4",
    "redux": "^3.5.2"
  },
  "devDependencies": {
    "babel": "^6.3.26",
    "babel-core": "^6.9.1",
    "babel-eslint": "^6.0.4",
    "babel-loader": "^6.2.4",
    "babel-plugin-add-module-exports": "^0.2.0",
    "babel-plugin-react-transform": "^2.0.0",
    "babel-plugin-transform-class-properties": "^6.9.1",
    "babel-plugin-transform-decorators-legacy": "^1.3.2",
    "babel-plugin-transform-flow-strip-types": "^6.7.0",
    "babel-preset-es2015": "^6.3.13",
    "babel-preset-es2015-webpack": "^6.4.1",
    "babel-preset-react": "^6.3.13",
    "babel-preset-react-optimize": "^1.0.1",
    "babel-preset-stage-0": "^6.3.13",
    "css-loader": "^0.23.0",
    "eslint": "^2.11.1",
    "eslint-config-airbnb": "^9.0.1",
    "eslint-plugin-flow-vars": "^0.4.0",
    "eslint-plugin-import": "^1.8.1",
    "eslint-plugin-jsx-a11y": "^1.2.2",
    "eslint-plugin-react": "^5.1.1",
    "expose-loader": "^0.7.1",
    "extract-text-webpack-plugin": "^1.0.1",
    "file-loader": "^0.8.5",
    "flow-bin": "^0.26.0",
    "iflow-immutable": "^1.0.32",
    "iflow-lodash": "^1.1.8",
    "iflow-react-redux": "^1.0.15",
    "iflow-react-router": "^1.1.7",
    "iflow-react-widgets": "^1.1.7",
    "iflow-redux": "^1.0.37",
    "iflow-redux-actions": "^1.0.3",
    "jscs": "^2.11.0",
    "json-loader": "^0.5.4",
    "lint-staged": "git:github.com/rvetere/lint-staged.git",
    "node-sass": "^3.4.2",
    "pre-commit": "^1.1.3",
    "react-transform-catch-errors": "^1.0.0",
    "react-transform-hmr": "^1.0.1",
    "redbox-react": "^1.2.0",
    "sass-lint": "^1.7.0",
    "sass-loader": "^3.1.2",
    "sass-resources-loader": "^1.0.2",
    "spacejam": "git:github.com/practicalmeteor/spacejam.git#meteor-test-1.3-rc.13",
    "style-loader": "^0.13.0",
    "url-loader": "^0.5.7",
    "webpack": "^1.13.0",
    "webpack-hot-middleware": "^2.4.1"
  },
```

**Comment by yourcelf** [comment]
Based on requests in https://github.com/AdmitHub/meteor-buildpack-horse/pull/105 we did recently change introduce `--production` flag when building node dependencies.  If your project had devDependencies specified that were required in order for the build to succeed, this would be the problem.

Could you try setting your buildpack to this earlier commit, so that npm won't use `--production`?
```
heroku buildpacks:set https://github.com/AdmitHub/meteor-buildpack-horse.git#8095a8dd898482142a12c91df3629e94ecd73bc5
```
We likely need to reconsider using `--production` in the pre-build `npm install`; and only use it in the post-build.

**Comment by rvetere** [comment]
Oh well this makes sense, totally! Yes i'm needing several devDependencies to actually build the project (especially the babel-loaders). I've just checked it today with another app we're developing and which is still deploying smoothly to heroku - there we have all the dependencies directly in "dependencies", why it is still working.

My problem is, that in this meteor project i'm using "spacejam" to run my unit-tests - and spacejam doesn't like it at all when i try to move all dev-dependencies to the normal dependencies (well he's kind of right, but it's ridiculous that a "test-runner" like spacejams fails on that and even changes my package.json again, but, other story)

So i just cleared the buildpacks for my app and added the particular version you mentioned again - in about 20mins i can say more.. just have to rerun the build-job again now.

**Comment by AdamBrodzinski** [comment]
Ahhh that makes sense. You may also want to try running `heroku config:set NPM_CONFIG_PRODUCTION=false` with the latest buildpack to see if that will make Heroku do the `npm install` webpack needs.

**Comment by yourcelf** [comment]
I've just pushed a change to master for this buildpack which removes the `--production` flag for the pre-build invocation of `npm install`, but keeps it for the post-build invocation. Let me know if this fixes it.

**Comment by rvetere** [comment]
Woa nice, it's working again with the latest change you pushed, thanks a lot for the great support! 👍

**Comment by tab00** [comment]
Couldn't you rewrite your code better? You shouldn't need devDependencies when deploying to a production environment as it's a waste of valuable resources. devDependencies should only be needed in a development environment.

Now my app can't be deployed to production using this buildpack because of the removal of the `--production` flag - installation of all the devDependencies created tens of thousands of files.

**Comment by rvetere** [comment]
@tab00 i see your point and... you're totally right oO My basic problem was only the stupid "spacejam" package (read above).

But in the meanwhile i kicked out spacejam and even the whole meteor testing level anyways (i'd rather test with standalone karma + enzyme completely bypassing meteor and mocking everything).

So now i would be able to rewrite my project so it could run again with the `production` flag inside.

But just to think it trough shortly... i normally can clearly distinct what package comes into which section - but what is about babel transpilers?

My first thought is "they're only needed for dev" - so i would put them into "devDependencies".. But this is not entirely true - to actually build a production artefact on heroku, the babel transpilers are needed indeed! But the final artefact running on production, doesn't need them at all anymore.

But this would still mean, that i'll have to move all my babel-transpilers to production right?

Well it is quite easy - basically i just have to clear all my devDependencies - then trying to build a production build - and re-adding all kind of packages he is missing in "dependencies" until he is satisfied again and the production build runs trough.

The ones that are remaining afterwards can go back to "devDependencies" and my build should just work on heroku, even with `production` flag...

Yes i can do that!

**Comment by yourcelf** [comment]
@tab00, can you say more about why the build fails for you now?

There are two moments when `npm install` runs.  The first is to prepare the environment to run `meteor build`, and the second is to install dependencies in the built package after `meteor build` has run.  The first one (I believe correctly) installs dev dependencies, as these may be necessary to build your app -- these may include webpack, transpilers, etc.  The second one (I believe correctly) uses `--production` to limit the files that are included when your project has been built.

Are you saying that dev files are being included in the built slug as a result of the first `npm install` run?  Can you share more about your setup and the repo?

**Comment by tab00** [comment]
Host: IBM Bluemix
App repository: https://github.com/meteor/todos

The app contains eslint devDependencies which creates over 17k files after running `npm install`.

When deploy it to Bluemix, the ENOSPC error is eventually thrown and the build is terminated.

I believe the cause is that the Linux environment in Bluemix has a limit to the number of files you can create. I think the default is 8192 files. I don't think this limit can be raised because Bluemix clients are not given sudo privileges.

When I deploy the todos app using my fork of meteor-buildpack-horse which has `npm set config production`, it is successful because the 17k new files of eslint are never created in the environment.

**Comment by yourcelf** [comment]
I see.  It's a shame that IBM Bluemix has this limitation -- but it's common for apps to require some  dev dependencies (e.g. transpiling, minifying, etc) in order to build the bundle; and this is a use case we want to support.  Other hosting targets (Heroku, self-hosted Dokku, etc) don't have that limitation on number of files.

It sounds like Bluemix may be a difficult environment for a project using npm, as npm generates *loads* of files, even for production builds.  This is especially true when combined with a strategy of building the project on the target server.  You might find that if your project grows in complexity, your non-dev dependencies will exceed that small limit as well.

I'm glad `npm config set production` in your fork is working for you now.  If that's not enough in the future, you might consider a strategy of building the meteor bundle locally, and then pushing the built files to Bluemix.  Or change hosting providers.  But I don't think the number of files is a bug in this buildpack; it's a consequence of its strategy of operation.
