### ISSUE TITLE
I cannot get this buildpack to work

### ISSUE THREAD

**Issue by usersxm** [AdmitHub/meteor-buildpack-horse#110]
My app is an out-of-box meteor app, with few things added. I set the env variables in heroku (mongo_url, root_url) but I cannot make it work... here it is the log displayed by heroku:
```
2016-06-09T20:05:30.585643+00:00 heroku[slug-compiler]: Slug compilation started
2016-06-09T20:05:30.585656+00:00 heroku[slug-compiler]: Slug compilation finished
2016-06-09T20:05:30.386521+00:00 heroku[api]: Deploy 7ba6e13 by alohanew@it.com
2016-06-09T20:05:30.386615+00:00 heroku[api]: Release v32 created by alohanew@it.com
2016-06-09T20:05:31.208006+00:00 heroku[web.1]: State changed from crashed to starting
2016-06-09T20:05:39.104608+00:00 heroku[web.1]: Starting process with command `.meteor/heroku_build/bin/node .meteor/heroku_build/app/main.js`
2016-06-09T20:05:42.314776+00:00 app[web.1]: 
2016-06-09T20:05:42.314821+00:00 app[web.1]: /app/.meteor/heroku_build/app/programs/server/node_modules/fibers/future.js:267
2016-06-09T20:05:42.315035+00:00 app[web.1]: 						throw(ex);
2016-06-09T20:05:42.315043+00:00 app[web.1]: 						      ^
2016-06-09T20:05:42.334046+00:00 app[web.1]: TypeError: Cannot call method 'connect' of undefined
2016-06-09T20:05:42.334055+00:00 app[web.1]:     at meteorInstall.server.kadira.js (server/kadira.js:3:8)
2016-06-09T20:05:42.334056+00:00 app[web.1]:     at fileEvaluate (packages/modules-runtime/.npm/package/node_modules/install/install.js:141:1)
2016-06-09T20:05:42.334057+00:00 app[web.1]:     at require (packages/modules-runtime/.npm/package/node_modules/install/install.js:75:1)
2016-06-09T20:05:42.334058+00:00 app[web.1]:     at /app/.meteor/heroku_build/app/programs/server/app/app.js:30:1
2016-06-09T20:05:42.334059+00:00 app[web.1]:     at /app/.meteor/heroku_build/app/programs/server/boot.js:283:10
2016-06-09T20:05:42.334060+00:00 app[web.1]:     at Array.forEach (native)
2016-06-09T20:05:42.334061+00:00 app[web.1]:     at Function._.each._.forEach (/app/.meteor/heroku_build/app/programs/server/node_modules/underscore/underscore.js:79:11)
2016-06-09T20:05:42.334062+00:00 app[web.1]:     at /app/.meteor/heroku_build/app/programs/server/boot.js:133:5
2016-06-09T20:05:43.369794+00:00 heroku[web.1]: Process exited with status 8
2016-06-09T20:05:43.386536+00:00 heroku[web.1]: State changed from starting to crashed
```

**Comment by usersxm** [comment]
It is working, there was some error in my code with the eslint and one thing that made me do... Close the issue please
