### ISSUE TITLE
Build fails with no apparent issue.

### ISSUE THREAD

**Issue by pandabrand** [AdmitHub/meteor-buildpack-horse#136]
Hi,  
Recently(past few days) my builds have started failing. I can't find any failures in the logs, or at least anything to me that looks like an error. These are the last few line of the log that I see with verbose turned on:    

```
+ echo -----> Building Meteor app with ROOT_URL: https://collide-travel.herokuapp.com
-----> Building Meteor app with ROOT_URL: https://collide-travel.herokuapp.com
+ mktemp -d /app/tmp/buildpacks/2a6b3cd8e392368665e034e859b6dd73daffd5ad6e476e155af3667bd21fdc765346a576e32db1450dd74e597a117a5b1c7e397b50e2d583268b716843bbe97a/build-XXXX
+ BUNDLE_DEST=/app/tmp/buildpacks/2a6b3cd8e392368665e034e859b6dd73daffd5ad6e476e155af3667bd21fdc765346a576e32db1450dd74e597a117a5b1c7e397b50e2d583268b716843bbe97a/build-gMFG
+ HOME=/app/tmp/cache/1.4.0.1 /app/tmp/cache/1.4.0.1/.meteor/meteor build --server https://collide-travel.herokuapp.com --server-only --directory /app/tmp/buildpacks/2a6b3cd8e392368665e034e859b6dd73daffd5ad6e476e155af3667bd21fdc765346a576e32db1450dd74e597a117a5b1c7e397b50e2d583268b716843bbe97a/build-gMFG
```

I'm pretty new to all this so I'm not sure exactly what I should be looking for,  things that may be of help.  Locally I am on node 6.1.0 and npm 3.8.6 the build is npm 3.10.5 and node 4.4.7.

**Comment by pandabrand** [comment]
When switching to the heroku/nodejs buildpack it will successfully build but doesn't run because it can't find meteor. it also reads the package.json and uses the node and npm version from that.

**Comment by yourcelf** [comment]
When you say "failing", do you mean the build is hanging or timing out?  What is the symptom you're seeing that lets you know that it's failing?  Are there no lines output during the build after what you included, and nothing pertinent in `heroku logs`?

**Comment by pandabrand** [comment]
What I get from tail the heroku logs  
```
2016-08-15T18:43:37.199122+00:00 heroku[web.1]: State changed from crashed to starting
2016-08-15T18:43:59.578944+00:00 heroku[web.1]: Starting process with command `node build/bundle/main.js`
2016-08-15T18:44:02.508478+00:00 app[web.1]:   throw new assert.AssertionError({
2016-08-15T18:44:02.511188+00:00 app[web.1]:     at wrapPathFunction (/app/build/bundle/programs/server/mini-files.js:77:10)
2016-08-15T18:44:02.508482+00:00 app[web.1]:         ^
2016-08-15T18:44:02.511190+00:00 app[web.1]:     at Object.Module._extensions..js (module.js:474:10)
2016-08-15T18:44:02.508150+00:00 app[web.1]: assert.js:93
2016-08-15T18:44:02.511186+00:00 app[web.1]: AssertionError: "undefined" === "function"
2016-08-15T18:44:02.511189+00:00 app[web.1]:     at Object.<anonymous> (/app/build/bundle/programs/server/mini-files.js:108:24)
2016-08-15T18:44:02.511190+00:00 app[web.1]:     at Module._compile (module.js:456:26)
2016-08-15T18:44:02.507784+00:00 app[web.1]: 
2016-08-15T18:44:02.511191+00:00 app[web.1]:     at Module.load (module.js:356:32)
2016-08-15T18:44:02.511191+00:00 app[web.1]:     at Function.Module._load (module.js:312:12)
2016-08-15T18:44:02.511192+00:00 app[web.1]:     at Module.require (module.js:364:17)
2016-08-15T18:44:02.511194+00:00 app[web.1]:     at Module._compile (module.js:456:26)
2016-08-15T18:44:02.511192+00:00 app[web.1]:     at require (module.js:380:17)
2016-08-15T18:44:02.511193+00:00 app[web.1]:     at Object.<anonymous> (/app/build/bundle/programs/server/boot.js:9:13)
2016-08-15T18:44:02.594691+00:00 heroku[web.1]: Process exited with status 8
2016-08-15T18:44:02.610812+00:00 heroku[web.1]: State changed from starting to crashed
2016-08-15T19:03:10.113878+00:00 heroku[slug-compiler]: Slug compilation started
```

**Comment by yourcelf** [comment]
What are the contents of `.meteor/release` in your project?

**Comment by pandabrand** [comment]
`METEOR@1.4.0.1`

**Comment by yourcelf** [comment]
Interesting, that error is one I'd expect to see from attempting to launch a meteor app targeting 1.4+ (which requires node v4) with node v0.10.  The problem is that node is not finding [`path.isAbsolute`](https://github.com/meteor/meteor/blob/05f65f9b2180efa6293289393e4fa0e3b1efa3a9/tools/static-assets/server/mini-files.js#L107-L108), a standard library function that is node v4+ only.

Can you please share a listing of the whole build, which would help indicate things like what version of nodejs is being found and used by the bundler?

(As a side note: if you're invoking `meteor` in local development, even if you have node v6 installed locally, meteor will use the version of node/npm that it bundles, which will be v4 for meteor 1.4.  You can use `meteor node --version` and `meteor npm --version` to see what versions meteor is using in local dev.)

**Comment by pandabrand** [comment]
Thank you, I'm still green in this meteor space, so it's `node 4.4.7` and `npm 3.10.5`.  
you can find my repo at:  
https://github.com/pandabrand/collide-travel

**Comment by yourcelf** [comment]
From within the project where you are building to heroku, could you please run:
```
heroku run .meteor/heroku_build/bin/node --version
```
This will indicate the version of node that the slug will be using to attempt to launch your built app.

**Comment by pandabrand** [comment]
I don't know if this is an issue or not. I wasn't using heroku remote to push my builds out. I just had the master branch connected to my heroku app to automatically build. Anyway that comes back with a `bash: .meteor/heroku_build/bin/node: No such file or directory` error when running that command. On the heroku side the build logs have this:  
```
+ echo -----> Using node: v4.4.7
-----> Using node: v4.4.7
+ /app/tmp/cache/1.4.0.1/.meteor/packages/meteor-tool/.1.4.0-1.13j49n2++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/bin/npm --version
+ echo ----->    and npm: 3.10.5
----->    and npm: 3.10.5
```

**Comment by yourcelf** [comment]
It seems clear the app is being bundled by the correct version of node, but it's being run by something else.  Again, could you please include the full build output?

That would include things like the moment when the build script [copies nodejs to `.meteor/heroku_build/bin`](https://github.com/AdmitHub/meteor-buildpack-horse/blob/master/bin/compile#L147-L151), which might tell us something about why you get "No such file or directory" for it.

Do you have something in place that changes the way the built app is executed?  e.g. some replacement for the buildpack's `bin/release`?  Do you have more than one buildpack installed at once?

**Comment by pandabrand** [comment]
I haven't consciously changed the build app execution. I'm still at the follow directions stage. I've only had one buildpack installed at a time.  
Here is the full build output.  
```
-----> Node.js app detected
+ dirname -- /app/tmp/buildpacks/2a6b3cd8e392368665e034e859b6dd73daffd5ad6e476e155af3667bd21fdc765346a576e32db1450dd74e597a117a5b1c7e397b50e2d583268b716843bbe97a/bin/compile
+ cd -P -- /app/tmp/buildpacks/2a6b3cd8e392368665e034e859b6dd73daffd5ad6e476e155af3667bd21fdc765346a576e32db1450dd74e597a117a5b1c7e397b50e2d583268b716843bbe97a/bin
+ cd ..
+ pwd -P
+ BUILDPACK_DIR=/app/tmp/buildpacks/2a6b3cd8e392368665e034e859b6dd73daffd5ad6e476e155af3667bd21fdc765346a576e32db1450dd74e597a117a5b1c7e397b50e2d583268b716843bbe97a
+ APP_CHECKOUT_DIR=/tmp/build_8864e7f19e21255c751eb780d00af0bf
+ CACHE_DIR=/app/tmp/cache
+ [ -n  ]
+ APP_SOURCE_DIR=/tmp/build_8864e7f19e21255c751eb780d00af0bf
+ [ -n  ]
+ [ ! -d /tmp/build_8864e7f19e21255c751eb780d00af0bf/.meteor ]
+ [ ! -d /tmp/build_8864e7f19e21255c751eb780d00af0bf/.meteor ]
+ sed -e s/METEOR@//
+ cat /tmp/build_8864e7f19e21255c751eb780d00af0bf/.meteor/release
+ APP_RELEASE=1.4.0.1
+ METEOR_DIR=/app/tmp/cache/1.4.0.1
+ COMPILE_DIR_SUFFIX=.meteor/heroku_build
+ COMPILE_DIR=/tmp/build_8864e7f19e21255c751eb780d00af0bf/.meteor/heroku_build
+ [ -z 1 ]
+ mkdir -p /tmp/build_8864e7f19e21255c751eb780d00af0bf /app/tmp/cache/1.4.0.1
+ mkdir -p /tmp/build_8864e7f19e21255c751eb780d00af0bf/.meteor/heroku_build /tmp/build_8864e7f19e21255c751eb780d00af0bf/.meteor/heroku_build/bin /tmp/build_8864e7f19e21255c751eb780d00af0bf/.meteor/heroku_build/lib
+ [ -z https://collide-travel.herokuapp.com ]
+ [ -z https://collide-travel.herokuapp.com ]
+ [ ! -e /app/tmp/cache/1.4.0.1/.meteor/meteor ]
+ METEOR=/app/tmp/cache/1.4.0.1/.meteor/meteor
+ HOME=/app/tmp/cache/1.4.0.1 /app/tmp/cache/1.4.0.1/.meteor/meteor --version
+ echo -----> Meteor version: Meteor 1.4.0.1
-----> Meteor version: Meteor 1.4.0.1
+ cd /tmp/build_8864e7f19e21255c751eb780d00af0bf
+ echo -----> Checking if this meteor version supports --server-only
-----> Checking if this meteor version supports --server-only
+ set +e
+ + HOME=/app/tmp/cache/1.4.0.1 /app/tmp/cache/1.4.0.1/.meteor/meteor help buildgrep -e --server-only
+ HAS_SERVER_ONLY=Usage: meteor build <output path> [--debug] [--directory] [--server-only]
Pass `--server-only` to skip building mobile apps, but still build the
  --server-only       Skip building mobile apps even if mobile platforms have
+ set -e
+ [ -n Usage: meteor build <output path> [--debug] [--directory] [--server-only]
Pass `--server-only` to skip building mobile apps, but still build the
  --server-only       Skip building mobile apps even if mobile platforms have ]
+ SERVER_ONLY_FLAG=--server-only
+ [ -z --server-only ]
+ find /app/tmp/cache/1.4.0.1 -wholename */dev_bundle/bin/npm
+ METEOR_NPM=/app/tmp/cache/1.4.0.1/.meteor/packages/meteor-tool/.1.4.0-1.13j49n2++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/bin/npm
+ find /app/tmp/cache/1.4.0.1 -wholename */dev_bundle/bin/node
+ METEOR_NODE=/app/tmp/cache/1.4.0.1/.meteor/packages/meteor-tool/.1.4.0-1.13j49n2++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/bin/node
+ echo /app/tmp/cache/1.4.0.1/.meteor/packages/meteor-tool/.1.4.0-1.13j49n2++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/bin/npm
+ sed -e s/[[:space:]]*$//
+ METEOR_NPM=/app/tmp/cache/1.4.0.1/.meteor/packages/meteor-tool/.1.4.0-1.13j49n2++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/bin/npm
+ + sed -e s/[[:space:]]*$//
echo /app/tmp/cache/1.4.0.1/.meteor/packages/meteor-tool/.1.4.0-1.13j49n2++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/bin/node
+ METEOR_NODE=/app/tmp/cache/1.4.0.1/.meteor/packages/meteor-tool/.1.4.0-1.13j49n2++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/bin/node
+ [ -z /app/tmp/cache/1.4.0.1/.meteor/packages/meteor-tool/.1.4.0-1.13j49n2++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/bin/npm ]
+ [ -z /app/tmp/cache/1.4.0.1/.meteor/packages/meteor-tool/.1.4.0-1.13j49n2++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/bin/node ]
+ NODE=/tmp/build_8864e7f19e21255c751eb780d00af0bf/.meteor/heroku_build/bin/node
+ cp /app/tmp/cache/1.4.0.1/.meteor/packages/meteor-tool/.1.4.0-1.13j49n2++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/bin/node /tmp/build_8864e7f19e21255c751eb780d00af0bf/.meteor/heroku_build/bin/node
+ chmod a+x /tmp/build_8864e7f19e21255c751eb780d00af0bf/.meteor/heroku_build/bin/node
+ dirname /app/tmp/cache/1.4.0.1/.meteor/packages/meteor-tool/.1.4.0-1.13j49n2++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/bin/npm
+ PATH=/app/tmp/cache/1.4.0.1/.meteor:/app/tmp/cache/1.4.0.1/.meteor/packages/meteor-tool/.1.4.0-1.13j49n2++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/bin:/tmp/build_8864e7f19e21255c751eb780d00af0bf/.meteor/heroku_build/bin:/app/bin:/app/vendor/bundle/bin:/app/vendor/bundle/ruby/2.3.0/bin:/usr/local/bin:/usr/bin:/bin:/tmp/codon/vendor/bin
+ /tmp/build_8864e7f19e21255c751eb780d00af0bf/.meteor/heroku_build/bin/node --version
+ echo -----> Using node: v4.4.7
-----> Using node: v4.4.7
+ /app/tmp/cache/1.4.0.1/.meteor/packages/meteor-tool/.1.4.0-1.13j49n2++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/bin/npm --version
+ echo ----->    and npm: 3.10.5
----->    and npm: 3.10.5
+ [ -e /tmp/build_8864e7f19e21255c751eb780d00af0bf/package.json ]
+ /app/tmp/cache/1.4.0.1/.meteor/packages/meteor-tool/.1.4.0-1.13j49n2++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/bin/npm install
npm WARN deprecated CSSselect@0.7.0: the module is now available as 'css-select'
npm WARN deprecated CSSwhat@0.4.7: the module is now available as 'css-what'
> buffertools@2.1.4 install /tmp/build_8864e7f19e21255c751eb780d00af0bf/node_modules/buffertools
> node-gyp rebuild
make: Entering directory `/tmp/build_8864e7f19e21255c751eb780d00af0bf/node_modules/buffertools/build'
  CXX(target) Release/obj.target/buffertools/buffertools.o
  SOLINK_MODULE(target) Release/obj.target/buffertools.node
  COPY Release/buffertools.node
make: Leaving directory `/tmp/build_8864e7f19e21255c751eb780d00af0bf/node_modules/buffertools/build'
> unicode@0.6.1 postinstall /tmp/build_8864e7f19e21255c751eb780d00af0bf/node_modules/unicode
> node install.js
try to read file /usr/share/unicode/UnicodeData.txt …
/usr/share/unicode/UnicodeData.txt not found.
try to read file /usr/share/unicode-data/UnicodeData.txt …
/usr/share/unicode-data/UnicodeData.txt not found.
try to read file UnicodeData.txt …
UnicodeData.txt not found.
try to download …
GET unicode.org:80/Public/UNIDATA/UnicodeData.txt
fetching …
saving data as Cc.js …
saving data as Zs.js …
saving data as Po.js …
saving data as Sc.js …
saving data as Ps.js …
saving data as Pe.js …
saving data as Sm.js …
saving data as Pd.js …
saving data as Nd.js …
saving data as Lu.js …
saving data as Sk.js …
saving data as Pc.js …
saving data as Ll.js …
saving data as So.js …
saving data as Lo.js …
saving data as Pi.js …
saving data as Cf.js …
saving data as No.js …
saving data as Pf.js …
saving data as Lt.js …
saving data as Lm.js …
saving data as Mn.js …
saving data as Me.js …
saving data as Mc.js …
saving data as Nl.js …
saving data as Zl.js …
saving data as Zp.js …
saving data as Cs.js …
saving data as Co.js …
done.
collide-travel@ /tmp/build_8864e7f19e21255c751eb780d00af0bf
├── actions@1.3.0 
├─┬ babel-plugin-transform-class-properties@6.11.5 
│ ├─┬ babel-helper-function-name@6.8.0 
│ │ ├── babel-helper-get-function-arity@6.8.0 
│ │ ├─┬ babel-template@6.9.0 
│ │ │ └── babylon@6.8.4 
│ │ ├─┬ babel-traverse@6.13.0 
│ │ │ ├─┬ babel-code-frame@6.11.0 
│ │ │ │ ├─┬ chalk@1.1.3 
│ │ │ │ │ ├── ansi-styles@2.2.1 
│ │ │ │ │ ├── escape-string-regexp@1.0.5 
│ │ │ │ │ ├─┬ has-ansi@2.0.0 
│ │ │ │ │ │ └── ansi-regex@2.0.0 
│ │ │ │ │ ├── strip-ansi@3.0.1 
│ │ │ │ │ └── supports-color@2.0.0 
│ │ │ │ └── js-tokens@2.0.0 
│ │ │ ├── babel-messages@6.8.0 
│ │ │ ├─┬ debug@2.2.0 
│ │ │ │ └── ms@0.7.1 
│ │ │ └── globals@8.18.0 
│ │ └─┬ babel-types@6.13.0 
│ │   ├── esutils@2.0.2 
│ │   └── to-fast-properties@1.0.2 
│ ├── babel-plugin-syntax-class-properties@6.13.0 
│ └─┬ babel-runtime@6.11.6 
│   ├── core-js@2.4.1 
│   └── regenerator-runtime@0.9.5 
├── bootstrap-sass@3.3.7 
├── classnames@2.2.5 
├── components@0.1.0 
├── faker@3.1.0 
├─┬ google-map-react@0.15.1 
│ ├── eventemitter3@1.2.0 
│ ├─┬ fbjs@0.8.3 
│ │ ├── core-js@1.2.7 
│ │ ├── immutable@3.8.1 
│ │ ├─┬ isomorphic-fetch@2.2.1 
│ │ │ ├─┬ node-fetch@1.6.0 
│ │ │ │ ├─┬ encoding@0.1.12 
│ │ │ │ │ └── iconv-lite@0.4.13 
│ │ │ │ └── is-stream@1.1.0 
│ │ │ └── whatwg-fetch@1.0.0 
│ │ ├─┬ promise@7.1.1 
│ │ │ └── asap@2.0.4 
│ │ └── ua-parser-js@0.7.10 
│ ├── point-geometry@0.0.0 
│ └── scriptjs@2.5.8 
├─┬ icons@0.1.1 
│ ├── async@0.1.22 
│ ├─┬ cheerio@0.10.8 
│ │ ├─┬ cheerio-select@0.0.3 
│ │ │ └─┬ CSSselect@0.7.0 
│ │ │   ├── boolbase@1.0.0 
│ │ │   ├── CSSwhat@0.4.7 
│ │ │   ├── domutils@1.4.3 
│ │ │   └── nth-check@1.0.1 
│ │ ├── entities@0.5.0 
│ │ ├─┬ htmlparser2@2.6.0 
│ │ │ ├── domelementtype@1.3.0 
│ │ │ ├── domhandler@2.0.3 
│ │ │ └── domutils@1.0.1 
│ │ └── underscore@1.4.4 
│ └─┬ request@2.12.0 
│   ├─┬ form-data@0.0.3 
│   │ ├── async@0.1.9 
│   │ └─┬ combined-stream@0.0.3 
│   │   └── delayed-stream@0.0.5 
│   └── mime@1.2.7 
├─┬ meteor-node-stubs@0.2.3 
│ ├── assert@1.3.0 
│ ├─┬ browserify-zlib@0.1.4 
│ │ └── pako@0.2.8 
│ ├─┬ buffer@4.5.1 
│ │ ├── base64-js@1.1.2 
│ │ ├── ieee754@1.1.6 
│ │ └── isarray@1.0.0 
│ ├─┬ console-browserify@1.1.0 
│ │ └── date-now@0.1.4 
│ ├── constants-browserify@1.0.0 
│ ├─┬ crypto-browserify@3.11.0 
│ │ ├─┬ browserify-cipher@1.0.0 
│ │ │ ├─┬ browserify-aes@1.0.6 
│ │ │ │ ├── buffer-xor@1.0.3 
│ │ │ │ └── cipher-base@1.0.2 
│ │ │ ├─┬ browserify-des@1.0.0 
│ │ │ │ ├── cipher-base@1.0.2 
│ │ │ │ └─┬ des.js@1.0.0 
│ │ │ │   └── minimalistic-assert@1.0.0 
│ │ │ └── evp_bytestokey@1.0.0 
│ │ ├─┬ browserify-sign@4.0.0 
│ │ │ ├── bn.js@4.11.1 
│ │ │ ├── browserify-rsa@4.0.1 
│ │ │ ├─┬ elliptic@6.2.3 
│ │ │ │ ├── brorand@1.0.5 
│ │ │ │ └── hash.js@1.0.3 
│ │ │ └─┬ parse-asn1@5.0.0 
│ │ │   ├─┬ asn1.js@4.5.2 
│ │ │   │ └── minimalistic-assert@1.0.0 
│ │ │   ├─┬ browserify-aes@1.0.6 
│ │ │   │ ├── buffer-xor@1.0.3 
│ │ │   │ └── cipher-base@1.0.2 
│ │ │   └── evp_bytestokey@1.0.0 
│ │ ├─┬ create-ecdh@4.0.0 
│ │ │ ├── bn.js@4.11.1 
│ │ │ └─┬ elliptic@6.2.3 
│ │ │   ├── brorand@1.0.5 
│ │ │   └── hash.js@1.0.3 
│ │ ├─┬ create-hash@1.1.2 
│ │ │ ├── cipher-base@1.0.2 
│ │ │ ├── ripemd160@1.0.1 
│ │ │ └── sha.js@2.4.5 
│ │ ├── create-hmac@1.1.4 
│ │ ├─┬ diffie-hellman@5.0.2 
│ │ │ ├── bn.js@4.11.1 
│ │ │ └─┬ miller-rabin@4.0.0 
│ │ │   └── brorand@1.0.5 
│ │ ├── inherits@2.0.1 
│ │ ├── pbkdf2@3.0.4 
│ │ ├─┬ public-encrypt@4.0.0 
│ │ │ ├── bn.js@4.11.1 
│ │ │ ├── browserify-rsa@4.0.1 
│ │ │ └─┬ parse-asn1@5.0.0 
│ │ │   ├─┬ asn1.js@4.5.2 
│ │ │   │ └── minimalistic-assert@1.0.0 
│ │ │   ├─┬ browserify-aes@1.0.6 
│ │ │   │ ├── buffer-xor@1.0.3 
│ │ │   │ └── cipher-base@1.0.2 
│ │ │   └── evp_bytestokey@1.0.0 
│ │ └── randombytes@2.0.3 
│ ├── domain-browser@1.1.7 
│ ├── events@1.1.0 
│ ├─┬ http-browserify@1.7.0 
│ │ ├── Base64@0.2.1 
│ │ └── inherits@2.0.1 
│ ├── https-browserify@0.0.1 
│ ├── os-browserify@0.2.1 
│ ├── path-browserify@0.0.0 
│ ├── process@0.11.2 
│ ├── punycode@1.4.1 
│ ├── querystring-es3@0.2.1 
│ ├─┬ readable-stream@2.0.6 
│ │ ├── core-util-is@1.0.2 
│ │ ├── inherits@2.0.1 
│ │ ├── isarray@1.0.0 
│ │ ├── process-nextick-args@1.0.6 
│ │ └── util-deprecate@1.0.2 
│ ├─┬ stream-browserify@2.0.1 
│ │ └── inherits@2.0.1 
│ ├── string_decoder@0.10.31 
│ ├── timers-browserify@1.4.2 
│ ├── tty-browserify@0.0.0 
│ ├─┬ url@0.11.0 
│ │ ├── punycode@1.3.2 
│ │ └── querystring@0.2.0 
│ ├─┬ util@0.10.3 
│ │ └── inherits@2.0.1 
│ └─┬ vm-browserify@0.0.4 
│   └── indexof@0.0.1 
├── momentjs@1.1.15 
├── pluralize@3.0.0 
├─┬ react@15.3.0 
│ ├─┬ loose-envify@1.2.0 
│ │ └── js-tokens@1.0.3 
│ └── object-assign@4.1.0 
├── react-addons-create-fragment@15.3.0 
├── react-addons-css-transition-group@15.3.0 
├── react-addons-linked-state-mixin@15.3.0 
├── react-addons-perf@15.3.0 
├── react-addons-pure-render-mixin@15.3.0 
├── react-addons-test-utils@15.3.0 
├── react-addons-transition-group@15.3.0 
├── react-addons-update@15.3.0 
├─┬ react-controllables@0.6.0 
│ ├── invariant@2.2.1 
│ ├── isarray@0.0.1 
│ ├─┬ lodash.mapvalues@3.0.1 
│ │ ├─┬ lodash._basecallback@3.3.1 
│ │ │ ├─┬ lodash._baseisequal@3.0.7 
│ │ │ │ └── lodash.istypedarray@3.0.6 
│ │ │ ├── lodash.isarray@3.0.4 
│ │ │ └── lodash.pairs@3.0.1 
│ │ ├── lodash._basefor@3.0.3 
│ │ └─┬ lodash.keys@3.1.2 
│ │   ├── lodash._getnative@3.9.1 
│ │   └── lodash.isarguments@3.1.0 
│ ├─┬ lodash.omit@3.1.0 
│ │ ├── lodash._arraymap@3.0.0 
│ │ ├─┬ lodash._basedifference@3.0.3 
│ │ │ ├── lodash._baseindexof@3.1.0 
│ │ │ ├── lodash._cacheindexof@3.0.2 
│ │ │ └── lodash._createcache@3.1.2 
│ │ ├── lodash._baseflatten@3.1.4 
│ │ ├── lodash._bindcallback@3.0.1 
│ │ ├── lodash._pickbyarray@3.0.2 
│ │ ├── lodash._pickbycallback@3.0.0 
│ │ ├── lodash.keysin@3.0.8 
│ │ └── lodash.restparam@3.6.1 
│ ├── lodash.pick@3.1.0 
│ └── object-keys@1.0.11 
├── react-dom@15.3.0 
├─┬ react-komposer@1.13.1 
│ ├── hoist-non-react-statics@1.2.0 
│ ├── mobx@2.4.3 
│ └── shallowequal@0.2.2 
├─┬ react-mixin@2.0.2 
│ ├── object-assign@2.1.1 
│ └── smart-mixin@1.2.1 
├─┬ react-mounter@1.2.0 
│ └── domready@1.0.8 
├── react-pure-render@1.0.2 
├─┬ react-redux@4.4.5 
│ └── lodash@4.15.0 
├── react-spinkit@1.1.8 
├─┬ redux@3.5.2 
│ ├── lodash-es@4.15.0 
│ └── symbol-observable@0.2.4 
├── redux-logger@2.6.1 
├── redux-thunk@2.1.0 
├─┬ slug@0.9.1 
│ └─┬ unicode@0.6.1 
│   └─┬ bufferstream@0.6.2 
│     ├── bufferjs@3.0.1 
│     └── buffertools@2.1.4 
└─┬ utils@0.3.1 
  ├─┬ any@1.0.0 
  │ └── make-iterator@0.1.1 
  ├── arr-diff@1.1.0 
  ├── arr-flatten@1.0.1 
  ├─┬ arr-map@2.0.0 
  │ └── make-iterator@0.1.1 
  ├── arr-union@3.1.0 
  ├── array-each@0.1.1 
  ├── array-slice@0.2.3 
  ├── array-unique@0.2.1 
  ├─┬ center-align@0.1.3 
  │ ├─┬ align-text@0.1.4 
  │ │ ├── kind-of@3.0.4 
  │ │ ├── longest@1.0.1 
  │ │ └── repeat-string@1.5.4 
  │ └── lazy-cache@1.0.4 
  ├── export-dirs@0.2.4 
  ├── export-files@2.1.1 
  ├── for-in@0.1.5 
  ├── for-own@0.1.4 
  ├── has-values@0.1.4 
  ├─┬ is-number@2.1.0 
  │ └── kind-of@3.0.4 
  ├─┬ is-plain-object@2.0.1 
  │ └── isobject@1.0.2 
  ├─┬ kind-of@2.0.1 
  │ └── is-buffer@1.1.4 
  ├─┬ make-iterator@0.2.1 
  │ └── kind-of@3.0.4 
  ├── object.defaults@0.3.0 
  ├─┬ object.filter@0.3.0 
  │ └── make-iterator@0.1.1 
  ├─┬ object.omit@2.0.0 
  │ └── is-extendable@0.1.1 
  ├─┬ object.pick@1.1.2 
  │ └─┬ isobject@2.1.0 
  │   └── isarray@1.0.0 
  ├── object.reduce@0.1.7 
  ├── right-align@0.1.3 
  ├── striptags@2.1.1 
  └── word-wrap@1.1.0 
+ [ -n  ]
+ echo -----> Building Meteor app with ROOT_URL: https://collide-travel.herokuapp.com
-----> Building Meteor app with ROOT_URL: https://collide-travel.herokuapp.com
+ mktemp -d /app/tmp/buildpacks/2a6b3cd8e392368665e034e859b6dd73daffd5ad6e476e155af3667bd21fdc765346a576e32db1450dd74e597a117a5b1c7e397b50e2d583268b716843bbe97a/build-XXXX
+ BUNDLE_DEST=/app/tmp/buildpacks/2a6b3cd8e392368665e034e859b6dd73daffd5ad6e476e155af3667bd21fdc765346a576e32db1450dd74e597a117a5b1c7e397b50e2d583268b716843bbe97a/build-4uQS
+ HOME=/app/tmp/cache/1.4.0.1 /app/tmp/cache/1.4.0.1/.meteor/meteor build --server https://collide-travel.herokuapp.com --server-only --directory /app/tmp/buildpacks/2a6b3cd8e392368665e034e859b6dd73daffd5ad6e476e155af3667bd21fdc765346a576e32db1450dd74e597a117a5b1c7e397b50e2d583268b716843bbe97a/build-4uQS
```

**Comment by pandabrand** [comment]
So I was able to get this deploy to work using `git push heroku master` instead of the autobuild on Heroku from on assigned branches. I also did a `meteor reset` and updated some meteor packages(I was flailing around for a solution). So it seems maybe the issue is with Heroku's build.

**Comment by yourcelf** [comment]
Interesting, thanks.  I hadn't tried using heroku autobuilds before, and you're the first to report an issue; so I'll leave this issue open and explore whether support for that is something that would be reasonable for us to add.
