### ISSUE TITLE
heroku crashes after deploying meteor 1.4.1.1

### ISSUE THREAD

**Issue by liorla** [AdmitHub/meteor-buildpack-horse#142]
hi!

hopefully someone can help...

we have just upgraded to meteor 1.4.1.1 and it's working well on our local machine. when we we deploy it to heroku, the app crashes with the following error:

"2016-08-31T15:22:59.274453+00:00 app[web.1]: assert.js:93
2016-08-31T15:22:59.274794+00:00 app[web.1]:   throw new assert.AssertionError({
2016-08-31T15:22:59.274798+00:00 app[web.1]:         ^
2016-08-31T15:22:59.277608+00:00 app[web.1]: AssertionError: "undefined" === "function"
2016-08-31T15:22:59.277609+00:00 app[web.1]:     at wrapPathFunction (/app/.meteor/heroku_build/app/programs/server/mini-files.js:77:10)
2016-08-31T15:22:59.277610+00:00 app[web.1]:     at Object.<anonymous> (/app/.meteor/heroku_build/app/programs/server/mini-files.js:108:24)
2016-08-31T15:22:59.277611+00:00 app[web.1]:     at Module._compile (module.js:456:26)
2016-08-31T15:22:59.277612+00:00 app[web.1]:     at Object.Module._extensions..js (module.js:474:10)
2016-08-31T15:22:59.277613+00:00 app[web.1]:     at Module.load (module.js:356:32)
2016-08-31T15:22:59.277613+00:00 app[web.1]:     at Function.Module._load (module.js:312:12)
2016-08-31T15:22:59.277614+00:00 app[web.1]:     at Module.require (module.js:364:17)
2016-08-31T15:22:59.277614+00:00 app[web.1]:     at require (module.js:380:17)
2016-08-31T15:22:59.277615+00:00 app[web.1]:     at Object.<anonymous> (/app/.meteor/heroku_build/app/programs/server/boot.js:9:13)
2016-08-31T15:22:59.277616+00:00 app[web.1]:     at Module._compile (module.js:456:26)
2016-08-31T15:22:59.371112+00:00 heroku[web.1]: Process exited with status 8
2016-08-31T15:23:04.083924+00:00 heroku[web.1]: Starting process with command `.meteor/heroku_build/bin/node .meteor/heroku_build/app/main.js`
2016-08-31T15:23:05.742142+00:00 app[web.1]:     at Module.load (module.js:356:32)
2016-08-31T15:23:05.740020+00:00 app[web.1]: 
2016-08-31T15:23:05.742142+00:00 app[web.1]:     at Function.Module._load (module.js:312:12)
2016-08-31T15:23:05.742135+00:00 app[web.1]:     at wrapPathFunction (/app/.meteor/heroku_build/app/programs/server/mini-files.js:77:10)
2016-08-31T15:23:05.742135+00:00 app[web.1]:     at Object.<anonymous> (/app/.meteor/heroku_build/app/programs/server/mini-files.js:108:24)
2016-08-31T15:23:05.742136+00:00 app[web.1]:     at Module._compile (module.js:456:26)
2016-08-31T15:23:05.742141+00:00 app[web.1]:     at Object.Module._extensions..js (module.js:474:10)
2016-08-31T15:23:05.740266+00:00 app[web.1]: assert.js:93
2016-08-31T15:23:05.742143+00:00 app[web.1]:     at Module.require (module.js:364:17)
2016-08-31T15:23:05.740493+00:00 app[web.1]:   throw new assert.AssertionError({
2016-08-31T15:23:05.742143+00:00 app[web.1]:     at require (module.js:380:17)
2016-08-31T15:23:05.740496+00:00 app[web.1]:         ^
2016-08-31T15:23:05.742143+00:00 app[web.1]:     at Object.<anonymous> (/app/.meteor/heroku_build/app/programs/server/boot.js:9:13)
2016-08-31T15:23:05.742125+00:00 app[web.1]: AssertionError: "undefined" === "function"
2016-08-31T15:23:05.742144+00:00 app[web.1]:     at Module._compile (module.js:456:26)
2016-08-31T15:23:05.818967+00:00 heroku[web.1]: Process exited with status 8
2016-08-31T15:23:05.847262+00:00 heroku[web.1]: State changed from starting to crashed
2016-08-31T15:23:47.515117+00:00 heroku[web.1]: State changed from crashed to starting
2016-08-31T15:23:55.289017+00:00 heroku[web.1]: Starting process with command `.meteor/heroku_build/bin/node .meteor/heroku_build/app/main.js`
2016-08-31T15:23:59.707002+00:00 heroku[web.1]: State changed from starting to crashed
2016-08-31T15:23:59.584904+00:00 app[web.1]: 
2016-08-31T15:23:59.585304+00:00 app[web.1]: assert.js:93
2016-08-31T15:23:59.585647+00:00 app[web.1]:   throw new assert.AssertionError({
2016-08-31T15:23:59.585651+00:00 app[web.1]:         ^
2016-08-31T15:23:59.603364+00:00 app[web.1]: AssertionError: "undefined" === "function"
2016-08-31T15:23:59.603367+00:00 app[web.1]:     at wrapPathFunction (/app/.meteor/heroku_build/app/programs/server/mini-files.js:77:10)
2016-08-31T15:23:59.603367+00:00 app[web.1]:     at Object.<anonymous> (/app/.meteor/heroku_build/app/programs/server/mini-files.js:108:24)
2016-08-31T15:23:59.603368+00:00 app[web.1]:     at Module._compile (module.js:456:26)
2016-08-31T15:23:59.603369+00:00 app[web.1]:     at Object.Module._extensions..js (module.js:474:10)
2016-08-31T15:23:59.603369+00:00 app[web.1]:     at Module.load (module.js:356:32)
2016-08-31T15:23:59.603370+00:00 app[web.1]:     at Function.Module._load (module.js:312:12)
2016-08-31T15:23:59.603371+00:00 app[web.1]:     at Module.require (module.js:364:17)
2016-08-31T15:23:59.603371+00:00 app[web.1]:     at require (module.js:380:17)
2016-08-31T15:23:59.603372+00:00 app[web.1]:     at Object.<anonymous> (/app/.meteor/heroku_build/app/programs/server/boot.js:9:13)
2016-08-31T15:23:59.603372+00:00 app[web.1]:     at Module._compile (module.js:456:26)
2016-08-31T15:23:59.713711+00:00 heroku[web.1]: Process exited with status 8"

any help would be greatly appreciated...

**Comment by liorla** [comment]
sorry.... updating to last buildpack solved it. :)
