### ISSUE TITLE
Getting a AssertionError: "undefined" === "function" when pushing

### ISSUE THREAD

**Issue by Jped** [AdmitHub/meteor-buildpack-horse#144]
Hi all, 
 I am a little new to meteor and heroku so please excuse me if this is a simple issue.

I am running one of the newer versions of meteor (1.4.1) and its node.js version is 4.5.

After pushing the heroku app I get the following error: 
```

2016-09-12T07:56:42.786286+00:00 app[web.1]: assert.js:93
2016-09-12T07:56:42.786521+00:00 app[web.1]:   throw new assert.AssertionError({
2016-09-12T07:56:42.786524+00:00 app[web.1]:         ^
2016-09-12T07:56:42.788035+00:00 app[web.1]: AssertionError: "undefined" === "function"
2016-09-12T07:56:42.788037+00:00 app[web.1]:     at wrapPathFunction (/app/build/bundle/programs/server/mini-files.js:77:10)
2016-09-12T07:56:42.788037+00:00 app[web.1]:     at Object.<anonymous> (/app/build/bundle/programs/server/mini-files.js:108:24)
2016-09-12T07:56:42.788038+00:00 app[web.1]:     at Module._compile (module.js:456:26)
2016-09-12T07:56:42.788038+00:00 app[web.1]:     at Object.Module._extensions..js (module.js:474:10)
2016-09-12T07:56:42.788039+00:00 app[web.1]:     at Module.load (module.js:356:32)
2016-09-12T07:56:42.788039+00:00 app[web.1]:     at Function.Module._load (module.js:312:12)
2016-09-12T07:56:42.788040+00:00 app[web.1]:     at Module.require (module.js:364:17)
2016-09-12T07:56:42.788041+00:00 app[web.1]:     at Object.<anonymous> (/app/build/bundle/programs/server/boot.js:9:13)
2016-09-12T07:56:42.788040+00:00 app[web.1]:     at require (module.js:380:17)
2016-09-12T07:56:42.788041+00:00 app[web.1]:     at Module._compile (module.js:456:26)
2016-09-12T07:56:42.868321+00:00 heroku[web.1]: State changed from starting to crashed
2016-09-12T13:39:46.392377+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/" host=jonpon.herokuapp.com request_id=bad357bd-e1e3-43c5-9e51-fb46f73161a3 fwd="199.98.16.5" dyno= connect= service= status=503 bytes=
2016-09-12T13:39:46.635477+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/favicon.ico" host=jonpon.herokuapp.com request_id=d4bbbe6b-dd5f-4cf8-9f33-3bb023ff5082 fwd="199.98.16.5" dyno= connect= service= status=503 bytes=

```

After doing some research I came across this https://github.com/meteor/meteor/issues/7475 thread which says it is some sort of issue with mup. I dont recall using mup so  I have no idea what they are referring to.

Is there any solution to this issue?

I was using the other meteor buildpack and switched to this one only to get the same issue...

**Comment by yourcelf** [comment]
That particular error is one that is typically thrown when you are attempting to run a Meteor 1.4+ app with node v0.10.x.  It looks like there might be something funny going on with setting the node version.

Could you share the contents of the `.meteor/release` file from your project?

What is the output of `heroku buildpacks` within your project?

Can you run `heroku config:set BUILDPACK_VERBOSE=1`, push to heroku, and share the output of the build operation?

**Comment by Jped** [comment]
.meteor/release : `METEOR@1.4.1`


heroku buildpacks : `=== jonpon Buildpack URL
https://github.com/AdmitHub/meteor-buildpack-horse.git
`

heroku config:set ... when i pushed it had the standard "everything up-to-date", the most recent error in the logs is : 
```
2016-09-13T03:50:10.605560+00:00 heroku[web.1]: Process exited with status 8
2016-09-13T03:50:10.542283+00:00 app[web.1]: assert.js:93
2016-09-13T03:50:10.541886+00:00 app[web.1]: 
2016-09-13T03:50:10.542530+00:00 app[web.1]:   throw new assert.AssertionError({
2016-09-13T03:50:10.542534+00:00 app[web.1]:         ^
2016-09-13T03:50:10.544447+00:00 app[web.1]: AssertionError: "undefined" === "function"
2016-09-13T03:50:10.544448+00:00 app[web.1]:     at wrapPathFunction (/app/build/bundle/programs/server/mini-files.js:77:10)
2016-09-13T03:50:10.544449+00:00 app[web.1]:     at Object.<anonymous> (/app/build/bundle/programs/server/mini-files.js:108:24)
2016-09-13T03:50:10.544450+00:00 app[web.1]:     at Module._compile (module.js:456:26)
2016-09-13T03:50:10.544450+00:00 app[web.1]:     at Object.Module._extensions..js (module.js:474:10)
2016-09-13T03:50:10.544451+00:00 app[web.1]:     at Module.load (module.js:356:32)
2016-09-13T03:50:10.544452+00:00 app[web.1]:     at Function.Module._load (module.js:312:12)
2016-09-13T03:50:10.544452+00:00 app[web.1]:     at Module.require (module.js:364:17)
2016-09-13T03:50:10.544453+00:00 app[web.1]:     at require (module.js:380:17)
2016-09-13T03:50:10.544453+00:00 app[web.1]:     at Object.<anonymous> (/app/build/bundle/programs/server/boot.js:9:13)
2016-09-13T03:50:10.544454+00:00 app[web.1]:     at Module._compile (module.js:456:26)
2016-09-13T03:50:10.626393+00:00 heroku[web.1]: State changed from starting to crashed
2016-09-13T03:50:10.627381+00:00 heroku[web.1]: State changed from crashed to starting

```

**Comment by yourcelf** [comment]
Sorry if I wasn't clear -- the log that would help me is the one of the build process itself (e.g. the output when you run `git push heroku`), not the heroku logs after the slug has been built.

**Comment by Jped** [comment]
Oh no worries, my bad.

It just returned the everything up-to-date

Here is a screenshot of the commands
![screenshot from 2016-09-13 15-19-30](https://cloud.githubusercontent.com/assets/5013466/18488012/8e49b366-79c5-11e6-8975-79c913b567ea.png)

**Comment by yourcelf** [comment]
To trigger a rebuild (which displays the build process), you'll need to make a new commit.  Heroku will only rebuild the slug if there are new commits since the last build.  You could do:

```
git commit --allow-empty -m "Rebuild, heroku"
```

and then `git push heroku master`.

**Comment by Jped** [comment]
Oh wow, it works now.

To review, basically what happened was that I needed to commit again after I changed the buildpack?

Thanks

**Comment by yourcelf** [comment]
No, the buildpack was the same.  But the commit triggered a _rebuild_.

The buildpack is a set of instructions for Heroku to rebuild your app.  It only executes those instructions if it thinks your app has changed; which you indicate by having new commits.

Glad it works!
