### ISSUE TITLE
 Problem in packages after deployment

### ISSUE THREAD

**Issue by Vaibhav241196** [AdmitHub/meteor-buildpack-horse#148]
Hello,

I used the okalnd:accounts-phone package in my development machine and everything worked fine.
But when i deployed it to heroku, the deployment process was successful but the app shows and error.

On checking the logs, i get the error as 

```
2016-09-26T04:16:11.541017+00:00 app[web.1]: /app/.meteor/heroku_build/app/programs/server/node_modules/fibers/future.js:280
2016-09-26T04:16:11.541033+00:00 app[web.1]:                        throw(ex);
2016-09-26T04:16:11.541034+00:00 app[web.1]:                        ^
2016-09-26T04:16:11.541039+00:00 app[web.1]: 
2016-09-26T04:16:11.541039+00:00 app[web.1]: TypeError: Cannot read property 'meteor' of undefined
2016-09-26T04:16:11.541040+00:00 app[web.1]:     at /app/.meteor/heroku_build/app/programs/server/packages/okland_accounts-phone.js:4:21 
2016-09-26T04:16:11.541041+00:00 app[web.1]:     at /app/.meteor/heroku_build/app/programs/server/packages/okland_accounts-phone.js:888:3
2016-09-26T04:16:11.541042+00:00 app[web.1]:     at /app/.meteor/heroku_build/app/programs/server/boot.js:297:10
2016-09-26T04:16:11.541042+00:00 app[web.1]:     at Array.forEach (native)
2016-09-26T04:16:11.541043+00:00 app[web.1]:     at Function._.each._.forEach (/app/.meteor/heroku_build/app/programs/server/node_modules/underscore/underscore.js:79:11)
2016-09-26T04:16:11.541044+00:00 app[web.1]:     at /app/.meteor/heroku_build/app/programs/server/boot.js:133:5
```

I checked the file accounts-phone.js to find out that the global variable Package is not defined

```
(function () {
/* Imports */

**var Meteor = Package.meteor.Meteor;**
var global = Package.meteor.global;
var meteorEnv = Package.meteor.meteorEnv;
var NpmModuleBcrypt = Package['npm-bcrypt'].NpmModuleBcrypt;
var Accounts = Package['accounts-base'].Accounts;

```

 help me with this issue as i have to deploy the app as per the deadline.
Thanks in advance

**Comment by gregory** [comment]
@Vaibhav241196 i get the same issue - found a fix?

**Comment by Vaibhav241196** [comment]
Hello @gregory ,
Yes I found the fix. Actually the environment variable BUILDPACK_PRELAUNCH_METEOR as explained in the readme file had to be set.
After setting that variable as 1 everything worked fine and I successfully deployed it to heroku

**Comment by gregory** [comment]
can you close this issue? :)
