### ISSUE TITLE
Problem when deploying Meteor 1.4+

### ISSUE THREAD

**Issue by GilbertMizrahi** [AdmitHub/meteor-buildpack-horse#150]
I get "Process exited with status 1". 
```
2016-10-14T23:09:55.765857+00:00 heroku[web.1]: Starting process with command `node server.js`
2016-10-14T23:09:57.421616+00:00 app[web.1]: module.js:327
2016-10-14T23:09:57.421630+00:00 app[web.1]:     throw err;
2016-10-14T23:09:57.421630+00:00 app[web.1]:     ^
2016-10-14T23:09:57.421631+00:00 app[web.1]:
2016-10-14T23:09:57.421632+00:00 app[web.1]: Error: Cannot find module '/app/server.js'
```

I guess the problem is with the ProcFile.
In the ProcFile I have:
`web: node server.js`

I haven't seen any example of what I should have in it. 
Anyone can give an example of what I should have in that file

**Comment by gregory** [comment]
@GilbertMizrahi if your app doesn't have a Procfile, one will be generated for you. 
Then from the logs you will see: `.meteor/heroku_build/bin/node .meteor/heroku_build/app/main.js`

So i guess, if for some reason you need to keep your Procfile, you could just replace yours with:
`web: .meteor/heroku_build/bin/node .meteor/heroku_build/app/main.js`

**Comment by GilbertMizrahi** [comment]
@gregory Initially I tried without a Procfile and it didn't work. I added the Procfile with the info you gave me, but I still have errors. This is what I get when I do: heroku logs --tail

```
2016-10-18T12:10:42.998953+00:00 heroku[web.1]: State changed from crashed to st
arting
2016-10-18T12:10:48.474451+00:00 heroku[web.1]: Starting process with command `.
meteor/heroku_build/bin/node .meteor/heroku_build/app/main.js`
2016-10-18T12:10:51.794862+00:00 app[web.1]:
        throw(ex);
2016-10-18T12:10:51.794846+00:00 app[web.1]:
2016-10-18T12:10:51.905119+00:00 app[web.1]: MongoError: Authentication failed.
2016-10-18T12:10:51.794861+00:00 app[web.1]: /app/.meteor/heroku_build/app/progr
ams/server/node_modules/fibers/future.js:313
2016-10-18T12:10:51.794863+00:00 app[web.1]:
        ^
2016-10-18T12:10:51.905123+00:00 app[web.1]:     at Object.Future.wait (/app/.me
teor/heroku_build/app/programs/server/node_modules/fibers/future.js:449:15)
2016-10-18T12:10:51.905124+00:00 app[web.1]:     at new MongoConnection (package
s/mongo/mongo_driver.js:219:27)
2016-10-18T12:10:51.905124+00:00 app[web.1]:     at new MongoInternals.RemoteCol
lectionDriver (packages/mongo/remote_collection_driver.js:4:16)
2016-10-18T12:10:51.905125+00:00 app[web.1]:     at Object.<anonymous> (packages
/mongo/remote_collection_driver.js:38:10)
2016-10-18T12:10:51.905125+00:00 app[web.1]:     at Object.defaultRemoteCollecti
onDriver (packages/underscore/underscore.js:750:1)
2016-10-18T12:10:51.905126+00:00 app[web.1]:     at new Mongo.Collection (packag
es/mongo/collection.js:103:40)
2016-10-18T12:10:51.905127+00:00 app[web.1]:     at AccountsServer.AccountsCommo
n (packages/accounts-base/accounts_common.js:23:18)
2016-10-18T12:10:51.905127+00:00 app[web.1]:     at new AccountsServer (packages
/accounts-base/accounts_server.js:18:5)
2016-10-18T12:10:51.905128+00:00 app[web.1]:     at meteorInstall.node_modules.m
eteor.accounts-base.server_main.js (packages/accounts-base/server_main.js:9:12)
2016-10-18T12:10:51.905130+00:00 app[web.1]:     - - - - -
2016-10-18T12:10:51.905132+00:00 app[web.1]:     at /app/.meteor/heroku_build/ap
p/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/li
b/connection/pool.js:462:72
2016-10-18T12:10:51.905129+00:00 app[web.1]:     at fileEvaluate (packages/modul
es-runtime/.npm/package/node_modules/install/install.js:153:1)
2016-10-18T12:10:51.905134+00:00 app[web.1]:     at Socket.<anonymous> (/app/.me
teor/heroku_build/app/programs/server/npm/node_modules/meteor/npm-mongo/node_mod
ules/mongodb-core/lib/connection/connection.js:306:22)
2016-10-18T12:10:51.905131+00:00 app[web.1]:     at Function.MongoError.create (
/app/.meteor/heroku_build/app/programs/server/npm/node_modules/meteor/npm-mongo/
node_modules/mongodb-core/lib/error.js:31:11)
2016-10-18T12:10:51.905132+00:00 app[web.1]:     at authenticateStragglers (/app
/.meteor/heroku_build/app/programs/server/npm/node_modules/meteor/npm-mongo/node
_modules/mongodb-core/lib/connection/pool.js:410:16)
2016-10-18T12:10:51.905133+00:00 app[web.1]:     at [object Object].messageHandl
er (/app/.meteor/heroku_build/app/programs/server/npm/node_modules/meteor/npm-mo
ngo/node_modules/mongodb-core/lib/connection/pool.js:444:5)
2016-10-18T12:10:51.905134+00:00 app[web.1]:     at emitOne (events.js:77:13)
2016-10-18T12:10:51.905135+00:00 app[web.1]:     at Socket.emit (events.js:169:7
)
2016-10-18T12:10:51.905136+00:00 app[web.1]:     at readableAddChunk (_stream_re
adable.js:153:18)
2016-10-18T12:10:51.905137+00:00 app[web.1]:     at TCP.onread (net.js:536:20)
2016-10-18T12:10:51.905136+00:00 app[web.1]:     at Socket.Readable.push (_strea
m_readable.js:111:10)
2016-10-18T12:10:52.019467+00:00 heroku[web.1]: State changed from starting to c
rashed
2016-10-18T12:10:52.002364+00:00 heroku[web.1]: Process exited with status 1
2016-10-18T16:01:55.322146+00:00 heroku[api]: Deploy 0712126 by gilbertmizrahi@g
mail.com
2016-10-18T16:01:55.322146+00:00 heroku[api]: Release v12 created by gilbertmizr
ahi@gmail.com
2016-10-18T16:01:55.646604+00:00 heroku[slug-compiler]: Slug compilation started

2016-10-18T16:01:55.646612+00:00 heroku[slug-compiler]: Slug compilation finishe
d
2016-10-18T16:01:55.801744+00:00 heroku[web.1]: State changed from crashed to st
arting
2016-10-18T16:02:03.187671+00:00 heroku[web.1]: Starting process with command `.
meteor/heroku_build/bin/node .meteor/heroku_build/app/main.js`
2016-10-18T16:02:10.979539+00:00 app[web.1]:
2016-10-18T16:02:10.979573+00:00 app[web.1]: /app/.meteor/heroku_build/app/progr
ams/server/node_modules/fibers/future.js:313
2016-10-18T16:02:10.979575+00:00 app[web.1]:
        throw(ex);
2016-10-18T16:02:10.979576+00:00 app[web.1]:
        ^
2016-10-18T16:02:11.204981+00:00 app[web.1]: MongoError: Authentication failed.
2016-10-18T16:02:11.204984+00:00 app[web.1]:     at Object.Future.wait (/app/.me
teor/heroku_build/app/programs/server/node_modules/fibers/future.js:449:15)
2016-10-18T16:02:11.204985+00:00 app[web.1]:     at new MongoConnection (package
s/mongo/mongo_driver.js:219:27)
2016-10-18T16:02:11.204985+00:00 app[web.1]:     at new MongoInternals.RemoteCol
lectionDriver (packages/mongo/remote_collection_driver.js:4:16)
2016-10-18T16:02:11.204986+00:00 app[web.1]:     at Object.<anonymous> (packages
/mongo/remote_collection_driver.js:38:10)
2016-10-18T16:02:11.204987+00:00 app[web.1]:     at Object.defaultRemoteCollecti
onDriver (packages/underscore/underscore.js:750:1)
2016-10-18T16:02:11.204988+00:00 app[web.1]:     at new Mongo.Collection (packag
es/mongo/collection.js:103:40)
2016-10-18T16:02:11.204988+00:00 app[web.1]:     at AccountsServer.AccountsCommo
n (packages/accounts-base/accounts_common.js:23:18)
2016-10-18T16:02:11.204989+00:00 app[web.1]:     at new AccountsServer (packages
/accounts-base/accounts_server.js:18:5)
2016-10-18T16:02:11.205005+00:00 app[web.1]:     at meteorInstall.node_modules.m
eteor.accounts-base.server_main.js (packages/accounts-base/server_main.js:9:12)
2016-10-18T16:02:11.205006+00:00 app[web.1]:     at fileEvaluate (packages/modul
es-runtime/.npm/package/node_modules/install/install.js:153:1)
2016-10-18T16:02:11.205007+00:00 app[web.1]:     - - - - -
2016-10-18T16:02:11.205014+00:00 app[web.1]:     at Function.MongoError.create (
/app/.meteor/heroku_build/app/programs/server/npm/node_modules/meteor/npm-mongo/
node_modules/mongodb-core/lib/error.js:31:11)
2016-10-18T16:02:11.205021+00:00 app[web.1]:     at /app/.meteor/heroku_build/ap
p/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/li
b/connection/pool.js:462:72
2016-10-18T16:02:11.205022+00:00 app[web.1]:     at authenticateStragglers (/app
/.meteor/heroku_build/app/programs/server/npm/node_modules/meteor/npm-mongo/node
_modules/mongodb-core/lib/connection/pool.js:410:16)
2016-10-18T16:02:11.205022+00:00 app[web.1]:     at [object Object].messageHandl
er (/app/.meteor/heroku_build/app/programs/server/npm/node_modules/meteor/npm-mo
ngo/node_modules/mongodb-core/lib/connection/pool.js:444:5)
2016-10-18T16:02:11.205023+00:00 app[web.1]:     at Socket.<anonymous> (/app/.me
teor/heroku_build/app/programs/server/npm/node_modules/meteor/npm-mongo/node_mod
ules/mongodb-core/lib/connection/connection.js:306:22)
2016-10-18T16:02:11.205024+00:00 app[web.1]:     at emitOne (events.js:77:13)
2016-10-18T16:02:11.205024+00:00 app[web.1]:     at Socket.emit (events.js:169:7
)
2016-10-18T16:02:11.205025+00:00 app[web.1]:     at readableAddChunk (_stream_re
adable.js:153:18)
2016-10-18T16:02:11.205026+00:00 app[web.1]:     at Socket.Readable.push (_strea
m_readable.js:111:10)
2016-10-18T16:02:11.205027+00:00 app[web.1]:     at TCP.onread (net.js:536:20)
2016-10-18T16:02:11.303032+00:00 heroku[web.1]: Process exited with status 1
2016-10-18T16:02:11.328506+00:00 heroku[web.1]: State changed from starting to c
rashed
2016-10-18T16:02:11.328506+00:00 heroku[web.1]: State changed from crashed to st
arting
2016-10-18T16:02:18.259321+00:00 heroku[web.1]: Starting process with command `.
meteor/heroku_build/bin/node .meteor/heroku_build/app/main.js`
2016-10-18T16:02:21.881480+00:00 app[web.1]:
2016-10-18T16:02:21.881495+00:00 app[web.1]: /app/.meteor/heroku_build/app/progr
ams/server/node_modules/fibers/future.js:313
2016-10-18T16:02:21.881496+00:00 app[web.1]:
        throw(ex);
2016-10-18T16:02:22.042471+00:00 app[web.1]: MongoError: Authentication failed.
2016-10-18T16:02:21.881497+00:00 app[web.1]:
        ^
2016-10-18T16:02:22.042474+00:00 app[web.1]:     at Object.Future.wait (/app/.me
teor/heroku_build/app/programs/server/node_modules/fibers/future.js:449:15)
2016-10-18T16:02:22.042475+00:00 app[web.1]:     at new MongoConnection (package
s/mongo/mongo_driver.js:219:27)
2016-10-18T16:02:22.042476+00:00 app[web.1]:     at new MongoInternals.RemoteCol
lectionDriver (packages/mongo/remote_collection_driver.js:4:16)
2016-10-18T16:02:22.042476+00:00 app[web.1]:     at Object.<anonymous> (packages
/mongo/remote_collection_driver.js:38:10)
2016-10-18T16:02:22.042477+00:00 app[web.1]:     at Object.defaultRemoteCollecti
onDriver (packages/underscore/underscore.js:750:1)
2016-10-18T16:02:22.042478+00:00 app[web.1]:     at new Mongo.Collection (packag
es/mongo/collection.js:103:40)
2016-10-18T16:02:22.042478+00:00 app[web.1]:     at AccountsServer.AccountsCommo
n (packages/accounts-base/accounts_common.js:23:18)
2016-10-18T16:02:22.042479+00:00 app[web.1]:     at new AccountsServer (packages
/accounts-base/accounts_server.js:18:5)
2016-10-18T16:02:22.042481+00:00 app[web.1]:     at fileEvaluate (packages/modul
es-runtime/.npm/package/node_modules/install/install.js:153:1)
2016-10-18T16:02:22.042480+00:00 app[web.1]:     at meteorInstall.node_modules.m
eteor.accounts-base.server_main.js (packages/accounts-base/server_main.js:9:12)
2016-10-18T16:02:22.042481+00:00 app[web.1]:     - - - - -
2016-10-18T16:02:22.042482+00:00 app[web.1]:     at Function.MongoError.create (
/app/.meteor/heroku_build/app/programs/server/npm/node_modules/meteor/npm-mongo/
node_modules/mongodb-core/lib/error.js:31:11)
2016-10-18T16:02:22.042483+00:00 app[web.1]:     at /app/.meteor/heroku_build/ap
p/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/li
b/connection/pool.js:462:72
2016-10-18T16:02:22.042485+00:00 app[web.1]:     at [object Object].messageHandl
er (/app/.meteor/heroku_build/app/programs/server/npm/node_modules/meteor/npm-mo
ngo/node_modules/mongodb-core/lib/connection/pool.js:444:5)
2016-10-18T16:02:22.042484+00:00 app[web.1]:     at authenticateStragglers (/app
/.meteor/heroku_build/app/programs/server/npm/node_modules/meteor/npm-mongo/node
_modules/mongodb-core/lib/connection/pool.js:410:16)
2016-10-18T16:02:22.042486+00:00 app[web.1]:     at Socket.<anonymous> (/app/.me
teor/heroku_build/app/programs/server/npm/node_modules/meteor/npm-mongo/node_mod
ules/mongodb-core/lib/connection/connection.js:306:22)
2016-10-18T16:02:22.042487+00:00 app[web.1]:     at emitOne (events.js:77:13)
2016-10-18T16:02:22.042487+00:00 app[web.1]:     at Socket.emit (events.js:169:7
)
2016-10-18T16:02:22.042488+00:00 app[web.1]:     at readableAddChunk (_stream_re
adable.js:153:18)
2016-10-18T16:02:22.042488+00:00 app[web.1]:     at Socket.Readable.push (_strea
m_readable.js:111:10)
2016-10-18T16:02:22.042489+00:00 app[web.1]:     at TCP.onread (net.js:536:20)
2016-10-18T16:02:22.152525+00:00 heroku[web.1]: Process exited with status 1
2016-10-18T16:02:22.196371+00:00 heroku[web.1]: State changed from starting to c
rashed
2016-10-18T16:02:23.887247+00:00 heroku[router]: at=error code=H10 desc="App cra
shed" method=GET path="/" host=cool-polls.herokuapp.com request_id=df284e13-ab0d
-4814-bc42-b8697f8811ef fwd="204.9.220.50" dyno= connect= service= status=503 by
tes=
2016-10-18T16:02:24.127123+00:00 heroku[router]: at=error code=H10 desc="App cra
shed" method=GET path="/" host=cool-polls.herokuapp.com request_id=b07013d3-0323
-4844-8701-f1ca07a81c95 fwd="204.9.220.50" dyno= connect= service= status=503 by
tes=
2016-10-18T16:02:25.510473+00:00 heroku[router]: at=error code=H10 desc="App cra
shed" method=GET path="/favicon.ico" host=cool-polls.herokuapp.com request_id=e6
aed1bb-64e9-41a9-9477-866739250fc8 fwd="204.9.220.50" dyno= connect= service= st
atus=503 bytes=
2016-10-18T16:05:02.535980+00:00 heroku[router]: at=error code=H10 desc="App cra
shed" method=GET path="/" host=cool-polls.herokuapp.com request_id=4721f8a9-40be
-4989-83b2-075cad3e426a fwd="204.9.220.50" dyno= connect= service= status=503 by
tes=
2016-10-18T16:05:03.454172+00:00 heroku[router]: at=error code=H10 desc="App cra
shed" method=GET path="/favicon.ico" host=cool-polls.herokuapp.com request_id=37
088067-d229-4054-9f9f-2bfbfda73bb7 fwd="204.9.220.50" dyno= connect= service= st
atus=503 bytes=
2016-10-18T16:05:06.452618+00:00 heroku[router]: at=error code=H10 desc="App cra
shed" method=GET path="/" host=cool-polls.herokuapp.com request_id=de3085e2-eb07
-4e52-8107-e560ac421952 fwd="204.9.220.50" dyno= connect= service= status=503 by
tes=
2016-10-18T16:05:07.030926+00:00 heroku[router]: at=error code=H10 desc="App cra
shed" method=GET path="/favicon.ico" host=cool-polls.herokuapp.com request_id=b3
b83314-e31d-4d29-b347-4e6d30756a10 fwd="204.9.220.50" dyno= connect= service= st
atus=503 bytes=
```
And this it what I see on the Application Logs:
```
2016-10-18T16:02:22.042486+00:00 app[web.1]:     at Socket.<anonymous> (/app/.meteor/heroku_build/app/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/connection/connection.js:306:22)
2016-10-18T16:02:22.042487+00:00 app[web.1]:     at emitOne (events.js:77:13)
2016-10-18T16:02:22.042487+00:00 app[web.1]:     at Socket.emit (events.js:169:7)
2016-10-18T16:02:22.042488+00:00 app[web.1]:     at readableAddChunk (_stream_readable.js:153:18)
2016-10-18T16:02:22.042488+00:00 app[web.1]:     at Socket.Readable.push (_stream_readable.js:111:10)
2016-10-18T16:02:22.042489+00:00 app[web.1]:     at TCP.onread (net.js:536:20)
2016-10-18T16:02:22.152525+00:00 heroku[web.1]: Process exited with status 1
2016-10-18T16:02:22.196371+00:00 heroku[web.1]: State changed from starting to crashed
2016-10-18T16:02:23.887247+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/" host=cool-polls.herokuapp.com request_id=df284e13-ab0d-4814-bc42-b8697f8811ef fwd="204.9.220.50" dyno= connect= service= status=503 bytes=
2016-10-18T16:02:24.127123+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/" host=cool-polls.herokuapp.com request_id=b07013d3-0323-4844-8701-f1ca07a81c95 fwd="204.9.220.50" dyno= connect= service= status=503 bytes=
2016-10-18T16:02:25.510473+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/favicon.ico" host=cool-polls.herokuapp.com request_id=e6aed1bb-64e9-41a9-9477-866739250fc8 fwd="204.9.220.50" dyno= connect= service= status=503 bytes=
2016-10-18T16:05:02.535980+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/" host=cool-polls.herokuapp.com request_id=4721f8a9-40be-4989-83b2-075cad3e426a fwd="204.9.220.50" dyno= connect= service= status=503 bytes=
2016-10-18T16:05:03.454172+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/favicon.ico" host=cool-polls.herokuapp.com request_id=37088067-d229-4054-9f9f-2bfbfda73bb7 fwd="204.9.220.50" dyno= connect= service= status=503 bytes=
2016-10-18T16:05:06.452618+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/" host=cool-polls.herokuapp.com request_id=de3085e2-eb07-4e52-8107-e560ac421952 fwd="204.9.220.50" dyno= connect= service= status=503 bytes=
2016-10-18T16:05:07.030926+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/favicon.ico" host=cool-polls.herokuapp.com request_id=b3b83314-e31d-4d29-b347-4e6d30756a10 fwd="204.9.220.50" dyno= connect= service= status=503 bytes=
```

Suggestions?

**Comment by gregory** [comment]
wired. i'm using this buildpack without procfile and works fine on heroku... 
Issue might not come from this buildpack. This in your error log `MongoError: Authentication failed.` sounds like you haven't set the mongo env variable properly.

**Comment by GilbertMizrahi** [comment]
I followed this instructions https://www.coshx.com/blog/2016/08/19/how-to-deploy-a-meteor-1-4-app-to-heroku/

Am I missing something else?

**Comment by GilbertMizrahi** [comment]
@gregory  I removed git from my project, delete the app from Heroku and started over. Now it works. Thanks.
