### ISSUE TITLE
SyntaxError: Unexpected token - unicodeNormalizePath

### ISSUE THREAD

**Issue by ccromnow** [AdmitHub/meteor-buildpack-horse#164]
##### Type of problem
Runtime problem after the build succeeds

##### Summary
The app build successfully and runs works locally. but when I deploy the app it crashes instantly (have treid two times one with a fully built app and one clean install of meteor).

##### Contents of `.meteor/release`
```
METEOR@1.4.3.1
```

can add these are the packages included:

```
meteor-base@1.0.4             # Packages every Meteor app needs to have
mobile-experience@1.0.4       # Packages for a great mobile UX
mongo@1.1.15                   # The database Meteor supports right now
blaze-html-templates@1.0.4 # Compile .html files into Meteor Blaze views
reactive-var@1.0.11            # Reactive variable for tracker
jquery@1.11.10                  # Helpful client-side library
tracker@1.1.2                 # Meteor's client-side reactive programming library

standard-minifier-css@1.3.3   # CSS minifier run for production mode
standard-minifier-js@1.2.2    # JS minifier run for production mode
es5-shim@4.6.15                # ECMAScript 5 compatibility for older browsers.
ecmascript@0.6.3              # Enable ECMAScript2015+ syntax in app code
shell-server@0.2.2            # Server-side component of the `meteor shell` command
```

##### Buildpack version
```
https://github.com/AdmitHub/meteor-buildpack-horse.git
```

##### Logs

```
2017-03-12T15:05:36.894412+00:00 app[web.1]: SyntaxError: Unexpected token >
2017-03-12T15:05:36.894415+00:00 app[web.1]:     at Object.Module._extensions..js (module.js:474:10)
2017-03-12T15:05:36.894414+00:00 app[web.1]:     at Module._compile (module.js:439:25)
2017-03-12T15:05:36.894415+00:00 app[web.1]:     at Module.load (module.js:356:32)
2017-03-12T15:05:36.894416+00:00 app[web.1]:     at Function.Module._load (module.js:312:12)
2017-03-12T15:05:36.894417+00:00 app[web.1]:     at Module.require (module.js:364:17)
2017-03-12T15:05:36.894417+00:00 app[web.1]:     at require (module.js:380:17)
2017-03-12T15:05:36.894437+00:00 app[web.1]:     at Object.<anonymous> (/app/build/bundle/programs/server/boot.js:9:13)
2017-03-12T15:05:36.894438+00:00 app[web.1]:     at Module._compile (module.js:456:26)
2017-03-12T15:05:36.894439+00:00 app[web.1]:     at Object.Module._extensions..js (module.js:474:10)
2017-03-12T15:05:36.894439+00:00 app[web.1]:     at Module.load (module.js:356:32)
2017-03-12T15:05:37.024035+00:00 heroku[web.1]: Process exited with status 8
2017-03-12T15:05:37.040373+00:00 heroku[web.1]: State changed from starting to crashed
2017-03-12T15:05:37.041584+00:00 heroku[web.1]: State changed from crashed to starting
2017-03-12T15:05:55.831142+00:00 heroku[web.1]: Starting process with command `node build/bundle/main.js`
2017-03-12T15:05:58.048059+00:00 app[web.1]: 
2017-03-12T15:05:58.048512+00:00 app[web.1]: /app/build/bundle/programs/server/mini-files.js:74
2017-03-12T15:05:58.048919+00:00 app[web.1]: const unicodeNormalizePath = (path) => {
2017-03-12T15:05:58.054022+00:00 app[web.1]:                                      ^
2017-03-12T15:05:58.054025+00:00 app[web.1]: SyntaxError: Unexpected token >
2017-03-12T15:05:58.054026+00:00 app[web.1]:     at Module._compile (module.js:439:25)
2017-03-12T15:05:58.054026+00:00 app[web.1]:     at Object.Module._extensions..js (module.js:474:10)
2017-03-12T15:05:58.054027+00:00 app[web.1]:     at Module.load (module.js:356:32)
2017-03-12T15:05:58.054028+00:00 app[web.1]:     at Function.Module._load (module.js:312:12)
2017-03-12T15:05:58.054028+00:00 app[web.1]:     at Module.require (module.js:364:17)
2017-03-12T15:05:58.054029+00:00 app[web.1]:     at require (module.js:380:17)
2017-03-12T15:05:58.054048+00:00 app[web.1]:     at Object.<anonymous> (/app/build/bundle/programs/server/boot.js:9:13)
2017-03-12T15:05:58.054050+00:00 app[web.1]:     at Module._compile (module.js:456:26)
2017-03-12T15:05:58.054050+00:00 app[web.1]:     at Object.Module._extensions..js (module.js:474:10)
2017-03-12T15:05:58.054051+00:00 app[web.1]:     at Module.load (module.js:356:32)
2017-03-12T15:05:58.117326+00:00 heroku[web.1]: State changed from starting to crashed
2017-03-12T15:05:58.126477+00:00 heroku[web.1]: Process exited with status 8
```

##### Deployment target
Heroku

**Comment by yourcelf** [comment]
It looks like the syntax error is a result of the arrow function syntax.  This seems to indicate that packages related to transpiling ES6 are not getting included.

By chance, is your .meteor/packages file listed in .gitignore?  Or is there any other reason you can think of that the ecmascript package might not be getting loaded correctly?

Can you include output of the build process that indicates the versions of node and npm found by the buildpack?

**Comment by ccromnow** [comment]
This is the build process:

```
remote: Compressing source files... done.
remote: Building source:
remote: 
remote: -----> meteor app detected
remote: 
remote: -----> Moving app source into a subdirectory
remote: 
remote:        Node engine:         0.10.40
remote:        Npm engine:          unspecified
remote:        Start mechanism:     none
remote:        node_modules source: none
remote:        node_modules cached: false
remote: 
remote:        NPM_CONFIG_PRODUCTION=true
remote:        NODE_MODULES_CACHE=true
remote: 
remote:        PRO TIP: Use 'npm init' and 'npm install --save' to define dependencies
remote:        See https://devcenter.heroku.com/articles/nodejs-support
remote: 
remote:        PRO TIP: Include a Procfile, package.json start script, or server.js file to start your app
remote:        See https://devcenter.heroku.com/articles/nodejs-support#runtime-behavior
remote: 
remote: -----> Installing binaries
remote:        Downloading and installing node 0.10.40...
remote: 
remote: -----> Building dependencies
remote:        Skipping dependencies (no source for node_modules)
remote: 
remote: -----> Checking startup method
remote: 
remote: -----> Finalizing build
remote:        Creating runtime environment
remote:        Exporting binary paths
remote:        Cleaning up build artifacts
remote:        Build successful!
remote:        /tmp/build_e1fbf364f2263a1492d4d952e00c2175
remote:        └── (empty)
remote:        
remote: 
remote: -----> Fetching Meteor 1.4.3.1
remote:        Using cached Meteor 1.4.3.1
remote: 
remote: -----> Unpacking Meteor 1.4.3.1
remote:        Meteor 1.4.3.1 is installed
remote: 
remote: -----> Building Meteor App Bundle
remote: 
remote: -----> Installing App's NPM Dependencies
remote:        npm WARN package.json meteor-dev-bundle@0.0.0 No description
remote:        npm WARN package.json meteor-dev-bundle@0.0.0 No repository field.
remote:        npm WARN package.json meteor-dev-bundle@0.0.0 No README data
remote:        
remote:        > fibers@1.0.15 install /tmp/build_e1fbf364f2263a1492d4d952e00c2175/build/bundle/programs/server/node_modules/fibers
remote:        > node build.js || nodejs build.js
remote:        
remote:        make: Entering directory `/tmp/build_e1fbf364f2263a1492d4d952e00c2175/build/bundle/programs/server/node_modules/fibers/build'
remote:          CXX(target) Release/obj.target/fibers/src/fibers.o
remote:          CXX(target) Release/obj.target/fibers/src/coroutine.o
remote:          CC(target) Release/obj.target/fibers/src/libcoro/coro.o
remote:          SOLINK_MODULE(target) Release/obj.target/fibers.node
remote:          SOLINK_MODULE(target) Release/obj.target/fibers.node: Finished
remote:          COPY Release/fibers.node
remote:        make: Leaving directory `/tmp/build_e1fbf364f2263a1492d4d952e00c2175/build/bundle/programs/server/node_modules/fibers/build'
remote:        Installed in `/tmp/build_e1fbf364f2263a1492d4d952e00c2175/build/bundle/programs/server/node_modules/fibers/bin/linux-x64-11/fibers.node`
remote:        
remote:        > meteor-dev-bundle@0.0.0 install /tmp/build_e1fbf364f2263a1492d4d952e00c2175/build/bundle/programs/server
remote:        > node npm-rebuild.js
remote:        
remote:        {
remote:          "http_parser": "1.0",
remote:          "node": "0.10.40",
remote:          "v8": "3.14.5.9",
remote:          "ares": "1.9.0-DEV",
remote:          "uv": "0.10.36",
remote:          "zlib": "1.2.8",
remote:          "modules": "11",
remote:          "openssl": "1.0.1p",
remote:          "npm": "1.4.28",
remote:          "meteor-dev-bundle": "0.0.0"
remote:        }
remote:        ansi-regex@0.2.1 node_modules/ansi-regex
remote:        
remote:        ansi-styles@1.1.0 node_modules/ansi-styles
remote:        
remote:        escape-string-regexp@1.0.5 node_modules/escape-string-regexp
remote:        
remote:        chalk@0.5.1 node_modules/chalk
remote:        
remote:        strip-ansi@0.3.0 node_modules/strip-ansi
remote:        
remote:        supports-color@0.2.0 node_modules/supports-color
remote:        
remote:        has-ansi@0.1.0 node_modules/has-ansi
remote:        
remote:        eachline@2.3.3 node_modules/eachline
remote:        
remote:        type-of@2.0.1 node_modules/type-of
remote:        
remote:        amdefine@1.0.1 node_modules/amdefine
remote:        
remote:        meteor-promise@0.8.0 node_modules/meteor-promise
remote:        
remote:        asap@2.0.5 node_modules/asap
remote:        
remote:        underscore@1.5.2 node_modules/underscore
remote:        
remote:        source-map-support@0.3.2 node_modules/source-map-support
remote:        
remote:        semver@4.1.0 node_modules/semver
remote:        
remote:        promise@7.1.1 node_modules/promise
remote:        
remote:        source-map@0.1.32 node_modules/source-map
remote:        
remote:        fibers@1.0.15 node_modules/fibers
remote: -----> Discovering process types
remote:        Procfile declares types     -> (none)
remote:        Default types for buildpack -> web
remote: 
remote: -----> Compressing...
remote:        Done: 164.7M
remote: -----> Launching...
remote:        Released v10
remote:        https://steffe.herokuapp.com/ deployed to Heroku
remote: 
remote: Verifying deploy... done.
```
The only thing in gitignore is node_modules/
package.json file looks like this:

```
{
  "name": "steffe",
  "private": true,
  "scripts": {
    "start": "meteor run"
  },
  "dependencies": {
    "babel-runtime": "^6.20.0",
    "meteor-node-stubs": "~0.2.4"
  }
}
```

**Comment by yourcelf** [comment]
That is not output from meteor-buildpack-horse. Some other heroku buildpack is running your build, and doing it with node v0.10.x, instead of v4.x as required by meteor v1.4+.

Please check the output of `heroku buildpacks:get`. To use meteor-buildpack-horse, you'll want to run:

    heroku buildpacks:set https://github.com/AdmitHub/meteor-buildpack-horse.git

**Comment by ccromnow** [comment]
wow... sorry to have wasted your time man, thanks a bunch, I'd been changing to your buildpack and was assuming i had made the switch. thanks a lot for your time.

**Comment by alexdorn87** [comment]
HI @ccromnow 
could you let me know how you fixed it?
