### ISSUE TITLE
Deployed but I am getting an "Unexpected Token >" error

### ISSUE THREAD

**Issue by ajitgoel** [AdmitHub/meteor-buildpack-horse#172]
2017-06-01T03:52:23.198182+00:00 app[api]: Initial release by user ajitgoel@gmai
l.com
2017-06-01T03:52:23.198182+00:00 app[api]: Release v1 created by user ajitgoel@g
mail.com
2017-06-01T03:52:23.512784+00:00 app[api]: Release v2 created by user ajitgoel@g
mail.com
2017-06-01T03:52:23.512784+00:00 app[api]: Enable Logplex by user ajitgoel@gmail
.com
2017-06-01T03:59:47.866255+00:00 app[api]: Attach MONGODB (@ref:mongolab-shaped-
23606) by user ajitgoel@gmail.com
2017-06-01T03:59:47.866255+00:00 app[api]: Release v3 created by user ajitgoel@g
mail.com
2017-06-01T04:12:49.691031+00:00 app[api]: Set MONGO_URL config vars by user aji
tgoel@gmail.com
2017-06-01T04:12:49.691031+00:00 app[api]: Release v4 created by user ajitgoel@g
mail.com
2017-06-01T04:14:19.445480+00:00 app[api]: Release v5 created by user ajitgoel@g
mail.com
2017-06-01T04:14:19.445480+00:00 app[api]: Set ROOT_URL config vars by user ajit
goel@gmail.com
2017-06-01T04:16:55.000000+00:00 app[api]: Build started by user ajitgoel@gmail.
com
2017-06-01T04:24:56.130797+00:00 app[api]: Deploy a497568c by user ajitgoel@gmai
l.com
2017-06-01T04:24:56.130797+00:00 app[api]: Release v6 created by user ajitgoel@g
mail.com
2017-06-01T04:24:56.152728+00:00 app[api]: Scaled to web@1:Free by user ajitgoel
@gmail.com
2017-06-01T04:16:55.000000+00:00 app[api]: Build succeeded
2017-06-01T04:25:19.895867+00:00 heroku[web.1]: Starting process with command `n
ode build/bundle/main.js`
2017-06-01T04:25:23.554389+00:00 heroku[web.1]: Process exited with status 8
2017-06-01T04:25:23.444974+00:00 app[web.1]:
2017-06-01T04:25:23.445336+00:00 app[web.1]: /app/build/bundle/programs/server/m
ini-files.js:82
2017-06-01T04:25:23.445714+00:00 app[web.1]: const unicodeNormalizePath = (path)
 => {
2017-06-01T04:25:23.445753+00:00 app[web.1]:
  ^
2017-06-01T04:25:23.450078+00:00 app[web.1]: SyntaxError: Unexpected token >
2017-06-01T04:25:23.450080+00:00 app[web.1]:     at Module._compile (module.js:4
39:25)
2017-06-01T04:25:23.450081+00:00 app[web.1]:     at Object.Module._extensions..j
s (module.js:474:10)
2017-06-01T04:25:23.450082+00:00 app[web.1]:     at Module.load (module.js:356:3
2)
2017-06-01T04:25:23.450082+00:00 app[web.1]:     at Function.Module._load (modul
e.js:312:12)
2017-06-01T04:25:23.450083+00:00 app[web.1]:     at Module.require (module.js:36
4:17)
2017-06-01T04:25:23.450084+00:00 app[web.1]:     at require (module.js:380:17)
2017-06-01T04:25:23.450085+00:00 app[web.1]:     at Object.<anonymous> (/app/bui
ld/bundle/programs/server/boot.js:9:13)
2017-06-01T04:25:23.450086+00:00 app[web.1]:     at Object.Module._extensions..j
s (module.js:474:10)
2017-06-01T04:25:23.450085+00:00 app[web.1]:     at Module._compile (module.js:4
56:26)
2017-06-01T04:25:23.450086+00:00 app[web.1]:     at Module.load (module.js:356:3
2)
2017-06-01T04:25:23.571429+00:00 heroku[web.1]: State changed from starting to c
rashed
2017-06-01T04:25:23.571429+00:00 heroku[web.1]: State changed from crashed to st
arting
2017-06-01T04:25:45.335815+00:00 heroku[web.1]: Starting process with command `n
ode build/bundle/main.js`
2017-06-01T04:25:46.802307+00:00 heroku[web.1]: Process exited with status 8
2017-06-01T04:25:46.753558+00:00 app[web.1]:
2017-06-01T04:25:46.753826+00:00 app[web.1]: /app/build/bundle/programs/server/m
ini-files.js:82
2017-06-01T04:25:46.754045+00:00 app[web.1]: const unicodeNormalizePath = (path)
 => {
2017-06-01T04:25:46.754085+00:00 app[web.1]:
  ^
2017-06-01T04:25:46.756879+00:00 app[web.1]: SyntaxError: Unexpected token >
2017-06-01T04:25:46.756880+00:00 app[web.1]:     at Module._compile (module.js:4
39:25)
2017-06-01T04:25:46.756880+00:00 app[web.1]:     at Object.Module._extensions..j
s (module.js:474:10)
2017-06-01T04:25:46.756880+00:00 app[web.1]:     at Module.load (module.js:356:3
2)
2017-06-01T04:25:46.756881+00:00 app[web.1]:     at Function.Module._load (modul
e.js:312:12)
2017-06-01T04:25:46.756881+00:00 app[web.1]:     at Module.require (module.js:36
4:17)
2017-06-01T04:25:46.756882+00:00 app[web.1]:     at require (module.js:380:17)
2017-06-01T04:25:46.756882+00:00 app[web.1]:     at Object.<anonymous> (/app/bui
ld/bundle/programs/server/boot.js:9:13)
2017-06-01T04:25:46.756883+00:00 app[web.1]:     at Module._compile (module.js:4
56:26)
2017-06-01T04:25:46.756883+00:00 app[web.1]:     at Object.Module._extensions..j
s (module.js:474:10)
2017-06-01T04:25:46.756883+00:00 app[web.1]:     at Module.load (module.js:356:3
2)
2017-06-01T04:25:46.816269+00:00 heroku[web.1]: State changed from starting to c
rashed
2017-06-01T04:36:12.615800+00:00 heroku[router]: at=error code=H10 desc="App cra
shed" method=GET path="/" host=simple-todos-angularjs.herokuapp.com request_id=4
fc9daf9-00f1-40f6-b938-a0f09c7eccef fwd="198.179.137.239" dyno= connect= service
= status=503 bytes= protocol=http
2017-06-01T04:36:14.911480+00:00 heroku[router]: at=error code=H10 desc="App cra
shed" method=GET path="/favicon.ico" host=simple-todos-angularjs.herokuapp.com r
equest_id=93fd8c91-d233-404f-b6c1-961bf42cc823 fwd="198.179.137.239" dyno= conne
ct= service= status=503 bytes= protocol=http
2017-06-01T04:40:37.511672+00:00 heroku[router]: at=error code=H10 desc="App cra
shed" method=GET path="/" host=simple-todos-angularjs.herokuapp.com request_id=c
2c008cb-5932-4de8-acef-40e50e058c05 fwd="198.179.137.239" dyno= connect= service
= status=503 bytes= protocol=https
2017-06-01T04:40:38.196171+00:00 heroku[router]: at=error code=H10 desc="App cra
shed" method=GET path="/favicon.ico" host=simple-todos-angularjs.herokuapp.com r
equest_id=59e7d846-c64c-4fb4-ba82-79b819c7b4e7 fwd="198.179.137.239" dyno= conne
ct= service= status=503 bytes= protocol=https

**Comment by yourcelf** [comment]
Apologies for the long delay in responding.  It looks as though heroku is using an old version of node against a codebase that uses a newer version of meteor.  Have you resolved this issue yet?  What is your target version of meteor (contents of `.meteor/release`), and what version of the buildpack are you using (output of `heroku buildpacks`)?
