### ISSUE TITLE
connection problems?

### ISSUE THREAD

**Issue by damon-t** [AdmitHub/meteor-buildpack-horse#214]
##### Type of problem

 - Failure to build

##### Summary

Hi, I can't deploy my app anymore. It seems there is a connection problem, but I don't know, if there is a general or specific problem. An if it is a specific problem, what could it be? I am clueless! :(

##### Contents of `.meteor/release`
```
METEOR@2.5
```

##### Buildpack version

https://github.com/AdmitHub/meteor-buildpack-horse.git

##### Logs

```
-----> Building on the Heroku-18 stack
-----> Using buildpack: https://github.com/AdmitHub/meteor-buildpack-horse
-----> Node.js app detected
+++ dirname -- /tmp/codon/tmp/buildpacks/6ec9c0780a117563073653c76abfcce030bc86ec/bin/compile
++ cd -P -- /tmp/codon/tmp/buildpacks/6ec9c0780a117563073653c76abfcce030bc86ec/bin
++ cd ..
++ pwd -P
+ BUILDPACK_DIR=/tmp/codon/tmp/buildpacks/6ec9c0780a117563073653c76abfcce030bc86ec
+ APP_CHECKOUT_DIR=/tmp/build_704497b6
+ CACHE_DIR=/tmp/codon/tmp/cache
+ '[' -n '' ']'
+ APP_SOURCE_DIR=/tmp/build_704497b6
+ '[' -n '' ']'
+ '[' '!' -d /tmp/build_704497b6/.meteor ']'
+ '[' '!' -d /tmp/build_704497b6/.meteor ']'
+ METEOR_DIR=/tmp/codon/tmp/cache/meteor
+ COMPILE_DIR_SUFFIX=.meteor/heroku_build
+ COMPILE_DIR=/tmp/build_704497b6/.meteor/heroku_build
+ '[' -z 1 ']'
+ mkdir -p /tmp/build_704497b6 /tmp/codon/tmp/cache/meteor
+ mkdir -p /tmp/build_704497b6/.meteor/heroku_build /tmp/build_704497b6/.meteor/heroku_build/bin /tmp/build_704497b6/.meteor/heroku_build/lib
+ '[' -z https://fly.omilia.de ']'
+ '[' -z https://fly.omilia.de ']'
+ '[' -e /tmp/codon/tmp/cache/meteor/.meteor/meteor ']'
+ echo '-----> Existing meteor installation found, using it.'
-----> Existing meteor installation found, using it.
+ cd /tmp/build_704497b6
++ METEOR --version
++ ARGS=--version
++ HOME=/tmp/codon/tmp/cache/meteor
++ /tmp/codon/tmp/cache/meteor/.meteor/meteor --version
Unable to update package catalog (are you offline?)
If you are using Meteor behind a proxy, set HTTP_PROXY and HTTPS_PROXY
environment variables or see this page for more details:
https://github.com/meteor/meteor/wiki/Using-Meteor-behind-a-proxy
This project says that it uses Meteor 2.5, but you don't have that version of
Meteor installed, and we were unable to contact Meteor's update servers to find
out about it. Please edit the .meteor/release file in the project and change it
to a valid Meteor release, or go online.
+ echo '-----> Target Meteor version: '
-----> Target Meteor version: 
+ echo '-----> Checking if this meteor version supports --server-only'
-----> Checking if this meteor version supports --server-only
+ set +e
++ METEOR help build
++ grep -e --server-only
++ ARGS='help build'
++ HOME=/tmp/codon/tmp/cache/meteor
++ /tmp/codon/tmp/cache/meteor/.meteor/meteor help build
Unable to update package catalog (are you offline?)
If you are using Meteor behind a proxy, set HTTP_PROXY and HTTPS_PROXY
environment variables or see this page for more details:
https://github.com/meteor/meteor/wiki/Using-Meteor-behind-a-proxy
This project says that it uses Meteor 2.5, but you don't have that version of
Meteor installed, and we were unable to contact Meteor's update servers to find
out about it. Please edit the .meteor/release file in the project and change it
to a valid Meteor release, or go online.
+ HAS_SERVER_ONLY=
+ set -e
+ '[' -n '' ']'
+ SERVER_ONLY_FLAG=
+ '[' -z '' ']'
+ echo '-----> Attempting to remove android platform.'
-----> Attempting to remove android platform.
+ METEOR remove-platform android
+ ARGS='remove-platform android'
+ HOME=/tmp/codon/tmp/cache/meteor
+ /tmp/codon/tmp/cache/meteor/.meteor/meteor remove-platform android
Unable to update package catalog (are you offline?)
If you are using Meteor behind a proxy, set HTTP_PROXY and HTTPS_PROXY
environment variables or see this page for more details:
https://github.com/meteor/meteor/wiki/Using-Meteor-behind-a-proxy
This project says that it uses Meteor 2.5, but you don't have that version of
Meteor installed, and we were unable to contact Meteor's update servers to find
out about it. Please edit the .meteor/release file in the project and change it
to a valid Meteor release, or go online.
+ true
+ echo '-----> Moving on.'
-----> Moving on.
++ METEOR node -e 'process.stdout.write(process.execPath)'
++ ARGS='node -e process.stdout.write(process.execPath)'
++ HOME=/tmp/codon/tmp/cache/meteor
++ /tmp/codon/tmp/cache/meteor/.meteor/meteor node -e 'process.stdout.write(process.execPath)'
+ METEOR_NODE=/tmp/codon/tmp/cache/meteor/.meteor/packages/meteor-tool/.1.8.3.ms2gpv.m1laf++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/dev_bundle/bin/node
++ dirname /tmp/codon/tmp/cache/meteor/.meteor/packages/meteor-tool/.1.8.3.ms2gpv.m1laf++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/dev_bundle/bin/node
+ METEOR_NPM=/tmp/codon/tmp/cache/meteor/.meteor/packages/meteor-tool/.1.8.3.ms2gpv.m1laf++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/dev_bundle/bin/npm
+ '[' -z /tmp/codon/tmp/cache/meteor/.meteor/packages/meteor-tool/.1.8.3.ms2gpv.m1laf++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/dev_bundle/bin/npm ']'
+ '[' -z /tmp/codon/tmp/cache/meteor/.meteor/packages/meteor-tool/.1.8.3.ms2gpv.m1laf++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/dev_bundle/bin/node ']'
+ NODE=/tmp/build_704497b6/.meteor/heroku_build/bin/node
+ cp /tmp/codon/tmp/cache/meteor/.meteor/packages/meteor-tool/.1.8.3.ms2gpv.m1laf++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/dev_bundle/bin/node /tmp/build_704497b6/.meteor/heroku_build/bin/node
+ chmod a+x /tmp/build_704497b6/.meteor/heroku_build/bin/node
++ dirname /tmp/codon/tmp/cache/meteor/.meteor/packages/meteor-tool/.1.8.3.ms2gpv.m1laf++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/dev_bundle/bin/npm
+ PATH=/tmp/codon/tmp/cache/meteor/.meteor:/tmp/codon/tmp/cache/meteor/.meteor/packages/meteor-tool/.1.8.3.ms2gpv.m1laf++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/dev_bundle/bin:/tmp/build_704497b6/.meteor/heroku_build/bin:/usr/local/bin:/usr/bin:/bin
++ /tmp/build_704497b6/.meteor/heroku_build/bin/node --version
+ echo '-----> Using node: v8.17.0'
-----> Using node: v8.17.0
++ /tmp/codon/tmp/cache/meteor/.meteor/packages/meteor-tool/.1.8.3.ms2gpv.m1laf++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/dev_bundle/bin/npm --version
+ echo '----->    and npm: 6.13.4'
----->    and npm: 6.13.4
+ '[' -e /tmp/build_704497b6/package.json ']'
+ /tmp/codon/tmp/cache/meteor/.meteor/packages/meteor-tool/.1.8.3.ms2gpv.m1laf++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/dev_bundle/bin/npm install
> nodent-runtime@3.2.1 install /tmp/build_704497b6/node_modules/nodent-runtime
> node build.js
## Built /tmp/build_704497b6/node_modules/nodent-runtime/dist/index.js
> bcrypt@5.0.1 install /tmp/build_704497b6/node_modules/bcrypt
> node-pre-gyp install --fallback-to-build
[bcrypt] Success: "/tmp/build_704497b6/node_modules/bcrypt/lib/binding/napi-v3/bcrypt_lib.node" is installed via remote
> node-sass@6.0.1 install /tmp/build_704497b6/node_modules/node-sass
> node scripts/install.js
Unable to save binary /tmp/build_704497b6/node_modules/node-sass/vendor/linux-x64-57 : { Error: ENOENT: no such file or directory, mkdir '/tmp/build_704497b6/node_modules/node-sass/vendor/linux-x64-57'
    at Object.fs.mkdirSync (fs.js:885:18)
    at checkAndDownloadBinary (/tmp/build_704497b6/node_modules/node-sass/scripts/install.js:113:8)
    at Object.<anonymous> (/tmp/build_704497b6/node_modules/node-sass/scripts/install.js:156:1)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Function.Module.runMain (module.js:694:10)
    at startup (bootstrap_node.js:204:16)
  errno: -2,
  code: 'ENOENT',
  syscall: 'mkdir',
  path: '/tmp/build_704497b6/node_modules/node-sass/vendor/linux-x64-57' }
> core-js@3.19.1 postinstall /tmp/build_704497b6/node_modules/canvg/node_modules/core-js
> node -e "try{require('./postinstall')}catch(e){}"
Thank you for using core-js ( https://github.com/zloirock/core-js ) for polyfilling JavaScript standard library!
The project needs your help! Please consider supporting of core-js:
> https://opencollective.com/core-js 
> https://patreon.com/zloirock 
> https://paypal.me/zloirock 
> bitcoin: bc1qlea7544qtsmj2rayg0lthvza9fau63ux0fstcz 
Also, the author of core-js ( https://github.com/zloirock ) is looking for a good job -)
> core-js@2.6.12 postinstall /tmp/build_704497b6/node_modules/core-js
> node -e "try{require('./postinstall')}catch(e){}"
Thank you for using core-js ( https://github.com/zloirock/core-js ) for polyfilling JavaScript standard library!
The project needs your help! Please consider supporting of core-js on Open Collective or Patreon: 
> https://opencollective.com/core-js 
> https://www.patreon.com/zloirock 
Also, the author of core-js ( https://github.com/zloirock ) is looking for a good job -)
> core-js@3.19.1 postinstall /tmp/build_704497b6/node_modules/jspdf/node_modules/core-js
> node -e "try{require('./postinstall')}catch(e){}"
> core-js@3.19.1 postinstall /tmp/build_704497b6/node_modules/tableexport.jquery.plugin/node_modules/core-js
> node -e "try{require('./postinstall')}catch(e){}"
> @fortawesome/fontawesome-free@5.15.4 postinstall /tmp/build_704497b6/node_modules/@fortawesome/fontawesome-free
> node attribution.js
Font Awesome Free 5.15.4 by @fontawesome - https://fontawesome.com
License - https://fontawesome.com/license/free (Icons: CC BY 4.0, Fonts: SIL OFL 1.1, Code: MIT License)
> cypress@7.7.0 postinstall /tmp/build_704497b6/node_modules/cypress
> node index.js --exec install
/tmp/build_704497b6/node_modules/is-installed-globally/index.js:12
	} catch {
	        ^
SyntaxError: Unexpected token {
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:617:28)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/tmp/build_704497b6/node_modules/cypress/lib/util.js:43:29)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.3.2 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! cypress@7.7.0 postinstall: `node index.js --exec install`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the cypress@7.7.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /app/.npm/_logs/2021-11-24T10_53_21_347Z-debug.log
 !     Push rejected, failed to compile Node.js app.
 !     Push failed
```

##### Deployment target
Heroku

**Comment by damon-t** [comment]
Hi,

I had to clear the build cache:

https://help.heroku.com/18PI5RSY/how-do-i-clear-the-build-cache
